#!/usr/bin/perl

use lib 'lib';
use Jemplate 0.10;

sub usage {
    warn <<'...';

Usage:
    jemplate -c|--compile template-file-list > output.js

...
    exit;
}

{
    if ($ARGV[0] =~ /^(-c|--compile)/) {
        shift @ARGV;
        usage() unless @ARGV;
        print Jemplate->compile_template_files(@ARGV);
    }
    else {
        usage();
    }
};
