/*
   This JavaScript code was generated by Jemplate, the JavaScript
   Template Toolkit. Any changes made to this file will be lost the next
   time the templates are compiled.

   Copyright 2006-2014 - Ingy döt Net - All rights reserved.
*/

if (typeof(Jemplate) == 'undefined')
    throw('Jemplate.js must be loaded before any Jemplate template files');

Jemplate.templateMap['kittys.html'] = function(context) {
    if (! context) throw('Jemplate function called without context\n');
    var stash = context.stash;
    var output = '';

    try {
output += '<h1>Flickr Kittys</h1>\n';
//line 6 "kittys.html"

// FOREACH 
(function() {
    var list = stash.get('items');
    list = new Jemplate.Iterator(list);
    var retval = list.get_first();
    var value = retval[0];
    var done = retval[1];
    var oldloop;
    try { oldloop = stash.get('loop') } finally {}
    stash.set('loop', list);
    try {
        while (! done) {
            stash.data['kitty'] = value;
output += '\n  <h2>';
//line 3 "kittys.html"
output += stash.get(['kitty', 0, 'title', 0]);
output += '</h2>\n  ';
//line 4 "kittys.html"
output += stash.get(['kitty', 0, 'author', 0]);
output += ' took this picture ';
//line 4 "kittys.html"
output += stash.get(['kitty', 0, 'date_taken', 0]);
output += '<br />\n  <a href="';
//line 5 "kittys.html"
output += stash.get(['kitty', 0, 'link', 0]);
output += '"><img src="';
//line 5 "kittys.html"
output += stash.get(['kitty', 0, 'media', 0, 'm', 0]);
output += '" /></a>\n';;
            retval = list.get_next();
            value = retval[0];
            done = retval[1];
        }
    }
    catch(e) {
        throw(context.set_error(e, output));
    }
    stash.set('loop', oldloop);
})();

output += '\n';
    }
    catch(e) {
        var error = context.set_error(e, output);
        throw(error);
    }

    return output;
}

