#============================================================= -*-Perl-*-
#
# Jemplate::Grammar
#
# DESCRIPTION
#   Grammar file for the Template Toolkit language containing token
#   definitions and parser state/rules tables generated by Parse::Yapp.
#
# AUTHOR
#   Ingy döt Net   <ingy@cpan.org>
#
# ORIGINAL AUTHOR
#   Andy Wardley   <abw@kfs.org>
#
# COPYRIGHT
#   Copyright (C) 2006-2008 Ingy döt Net.
#   Copyright (C) 1996-2000 Andy Wardley.
#   Copyright (C) 1998-2000 Canon Research Centre Europe Ltd.
#
#   This module is free software; you can redistribute it and/or
#   modify it under the same terms as Perl itself.
#
#------------------------------------------------------------------------
#
# NOTE: this module is constructed from the parser/Grammar.pm.skel
# file by running the parser/yc script.  You only need to do this if 
# you have modified the grammar in the parser/Parser.yp file and need
# to-recompile it.  See the README in the 'parser' directory for more
# information (sub-directory of the Jemplate distribution).
#
#========================================================================

package Jemplate::Grammar;

require 5.004;

use strict;
use vars qw( $VERSION );

$VERSION  = sprintf("%d.%02d", q$Revision: 2.10 $ =~ /(\d+)\.(\d+)/);

my (@RESERVED, %CMPOP, $LEXTABLE, $RULES, $STATES);
my ($factory, $rawstart);


#========================================================================
# Reserved words, comparison and binary operators
#========================================================================

@RESERVED = qw( 
	GET CALL SET DEFAULT INSERT INCLUDE PROCESS WRAPPER BLOCK END
	USE RAW PLUGIN FILTER MACRO JAVASCRIPT TO STEP AND OR NOT DIV MOD
	IF UNLESS ELSE ELSIF FOR NEXT WHILE SWITCH CASE META IN
	TRY THROW CATCH FINAL LAST RETURN STOP CLEAR VIEW DEBUG
    );

# for historical reasons, != and == are converted to ne and eq to perform 
# stringwise comparison (mainly because it doesn't generate "non-numerical 
# comparison" warnings which != and == can) but the others (e.g. < > <= >=)
# are not converted to their stringwise equivalents.  I added 'gt' et al, 
# briefly for v2.04d and then took them out again in 2.04e.

%CMPOP = qw( 
    != !=
    == ==
    <  <
    >  >
    >= >=
    <= <=
);


#========================================================================
# Lexer Token Table
#========================================================================

# lookup table used by lexer is initialised with special-cases
$LEXTABLE = {
    'FOREACH' => 'FOR',
    'BREAK'   => 'LAST',
    '&&'      => 'AND',
    '||'      => 'OR',
    '!'       => 'NOT',
    '|'	      => 'FILTER',
    '.'       => 'DOT',
    '_'       => 'CAT',
    '..'      => 'TO',
#    ':'       => 'MACRO',
    '='       => 'ASSIGN',
    '=>'      => 'ASSIGN',
#    '->'      => 'ARROW',
    ','       => 'COMMA',
    '\\'      => 'REF',
    'and'     => 'AND',		# explicitly specified so that qw( and or
    'or'      => 'OR',		# not ) can always be used in lower case, 
    'not'     => 'NOT',		# regardless of ANYCASE flag
    'mod'     => 'MOD',
    'div'     => 'DIV',
};

# localise the temporary variables needed to complete lexer table
{ 
#    my @tokens = qw< ( ) [ ] { } ${ $ / ; : ? >;
    my @tokens = qw< ( ) [ ] { } ${ $ + / ; : ? >;
    my @cmpop  = keys %CMPOP;
#    my @binop  = qw( + - * % );              # '/' above, in @tokens
    my @binop  = qw( - * % );              # '+' and '/' above, in @tokens

    # fill lexer table, slice by slice, with reserved words and operators
    @$LEXTABLE{ @RESERVED, @cmpop, @binop, @tokens } 
	= ( @RESERVED, ('CMPOP') x @cmpop, ('BINOP') x @binop, @tokens );
}


#========================================================================
# CLASS METHODS
#========================================================================

sub new {
    my $class = shift;
    bless {
	LEXTABLE => $LEXTABLE,
	STATES   => $STATES,
	RULES    => $RULES,
    }, $class;
}

# update method to set package-scoped $factory lexical 
sub install_factory {
    my ($self, $new_factory) = @_;
    $factory = $new_factory;
}


#========================================================================
# States
#========================================================================

$STATES = [
	{#State 0
		ACTIONS => {
			'WHILE' => 12,
			'CLEAR' => 49,
			'META' => 54,
			'UNLESS' => 17,
			'THROW' => 16,
			"[" => 52,
			'FILTER' => 53,
			'TRY' => 20,
			";" => -19,
			'JAVASCRIPT' => 58,
			'WRAPPER' => 57,
			'DEBUG' => 2,
			'REF' => 1,
			'DEFAULT' => 42,
			'FOR' => 44,
			'USE' => 5,
			'NEXT' => 4,
			'STOP' => 3,
			'LAST' => 9,
			'RETURN' => 46,
			'SWITCH' => 8,
			'GET' => 45,
			'perl' => 48,
			'NUMBER' => 47,
			'LITERAL' => 34,
			'MACRO' => 67,
			'TEXT' => 35,
			'BLOCK' => 71,
			'NOT' => 37,
			"{" => 75,
			"(" => 74,
			'PROCESS' => 39,
			'INCLUDE' => 62,
			'SET' => 23,
			'IDENT' => 22,
			'VIEW' => 61,
			'rawperl' => 28,
			"\${" => 63,
			'RAW' => 31,
			'IF' => 32,
			'CALL' => 66,
			'INSERT' => 65,
			"\"" => 30,
			"\$" => 29
		},
		DEFAULT => -3,
		GOTOS => {
			'anonblock' => 10,
			'defblockname' => 7,
			'template' => 6,
			'item' => 43,
			'javascript' => 19,
			'macro' => 60,
			'filter' => 21,
			'statement' => 59,
			'ident' => 56,
			'condition' => 50,
			'chunks' => 13,
			'view' => 11,
			'capture' => 15,
			'sterm' => 55,
			'node' => 18,
			'loop' => 14,
			'setlist' => 51,
			'expr' => 27,
			'atomexpr' => 26,
			'try' => 33,
			'raw' => 64,
			'switch' => 25,
			'defblock' => 24,
			'block' => 38,
			'atomdir' => 70,
			'use' => 72,
			'wrapper' => 40,
			'term' => 41,
			'directive' => 73,
			'assign' => 69,
			'lterm' => 36,
			'chunk' => 68
		}
	},
	{#State 1
		ACTIONS => {
			"\$" => 29,
			'IDENT' => 22,
			"\${" => 63
		},
		GOTOS => {
			'ident' => 76,
			'item' => 43,
			'node' => 18
		}
	},
	{#State 2
		ACTIONS => {
			'LITERAL' => 80,
			'IDENT' => 79,
			'NUMBER' => 84,
			"\"" => 78,
			'FILENAME' => 86,
			"\$" => 77
		},
		GOTOS => {
			'names' => 83,
			'filepart' => 81,
			'name' => 85,
			'filename' => 82,
			'nameargs' => 87
		}
	},
	{#State 3
		DEFAULT => -39
	},
	{#State 4
		DEFAULT => -42
	},
	{#State 5
		ACTIONS => {
			'IDENT' => 88,
			'LITERAL' => 92,
			"\${" => 63,
			"\$" => 90,
			'FILENAME' => 86,
			"\"" => 89,
			'NUMBER' => 84
		},
		GOTOS => {
			'item' => 94,
			'lvalue' => 93,
			'filepart' => 81,
			'name' => 85,
			'filename' => 82,
			'lnameargs' => 91,
			'names' => 83,
			'nameargs' => 95
		}
	},
	{#State 6
		ACTIONS => {
			'' => 96
		}
	},
	{#State 7
		ACTIONS => {
			'IDENT' => 100
		},
		DEFAULT => -88,
		GOTOS => {
			'metadata' => 98,
			'blockargs' => 99,
			'meta' => 97
		}
	},
	{#State 8
		ACTIONS => {
			'LITERAL' => 102,
			'IDENT' => 22,
			'REF' => 1,
			"[" => 52,
			"\${" => 63,
			'NOT' => 37,
			"{" => 75,
			'NUMBER' => 47,
			"(" => 74,
			"\"" => 30,
			"\$" => 29
		},
		GOTOS => {
			'expr' => 103,
			'term' => 41,
			'sterm' => 55,
			'node' => 18,
			'lterm' => 36,
			'item' => 43,
			'ident' => 101
		}
	},
	{#State 9
		DEFAULT => -41
	},
	{#State 10
		DEFAULT => -10
	},
	{#State 11
		DEFAULT => -15
	},
	{#State 12
		ACTIONS => {
			"(" => 74,
			'NUMBER' => 47,
			"{" => 75,
			"\$" => 29,
			"\"" => 30,
			"\${" => 63,
			'NOT' => 37,
			"[" => 52,
			'LITERAL' => 102,
			'REF' => 1,
			'IDENT' => 22
		},
		GOTOS => {
			'lterm' => 36,
			'term' => 41,
			'sterm' => 55,
			'node' => 18,
			'ident' => 101,
			'item' => 43,
			'expr' => 104
		}
	},
	{#State 13
		ACTIONS => {
			'INCLUDE' => 62,
			'SET' => 23,
			'IDENT' => 22,
			'VIEW' => 61,
			'RAW' => 31,
			'IF' => 32,
			'CALL' => 66,
			'INSERT' => 65,
			"\"" => 30,
			"\$" => 29,
			'rawperl' => 28,
			"\${" => 63,
			'TEXT' => 35,
			'LITERAL' => 34,
			'MACRO' => 67,
			"{" => 75,
			"(" => 74,
			'PROCESS' => 39,
			'BLOCK' => 71,
			'NOT' => 37,
			'FOR' => 44,
			'NEXT' => 4,
			'USE' => 5,
			'STOP' => 3,
			'DEBUG' => 2,
			'REF' => 1,
			'DEFAULT' => 42,
			'NUMBER' => 47,
			'perl' => 48,
			'LAST' => 9,
			'RETURN' => 46,
			'SWITCH' => 8,
			'GET' => 45,
			'META' => 54,
			"[" => 52,
			'FILTER' => 53,
			'UNLESS' => 17,
			'THROW' => 16,
			'WHILE' => 12,
			'CLEAR' => 49,
			'JAVASCRIPT' => 58,
			'WRAPPER' => 57,
			'TRY' => 20,
			";" => -19
		},
		DEFAULT => -2,
		GOTOS => {
			'item' => 43,
			'switch' => 25,
			'defblockname' => 7,
			'defblock' => 24,
			'raw' => 64,
			'try' => 33,
			'anonblock' => 10,
			'atomexpr' => 26,
			'expr' => 27,
			'setlist' => 51,
			'loop' => 14,
			'chunk' => 105,
			'sterm' => 55,
			'node' => 18,
			'assign' => 69,
			'lterm' => 36,
			'capture' => 15,
			'view' => 11,
			'condition' => 50,
			'directive' => 73,
			'ident' => 56,
			'statement' => 59,
			'macro' => 60,
			'term' => 41,
			'filter' => 21,
			'wrapper' => 40,
			'use' => 72,
			'javascript' => 19,
			'atomdir' => 70
		}
	},
	{#State 14
		DEFAULT => -24
	},
	{#State 15
		DEFAULT => -11
	},
	{#State 16
		ACTIONS => {
			'LITERAL' => 80,
			'IDENT' => 79,
			'NUMBER' => 84,
			"\$" => 77,
			'FILENAME' => 86,
			"\"" => 78
		},
		GOTOS => {
			'names' => 83,
			'nameargs' => 106,
			'filepart' => 81,
			'name' => 85,
			'filename' => 82
		}
	},
	{#State 17
		ACTIONS => {
			"{" => 75,
			'NUMBER' => 47,
			"(" => 74,
			"\"" => 30,
			"\$" => 29,
			"\${" => 63,
			'NOT' => 37,
			"[" => 52,
			'LITERAL' => 102,
			'IDENT' => 22,
			'REF' => 1
		},
		GOTOS => {
			'expr' => 107,
			'term' => 41,
			'sterm' => 55,
			'node' => 18,
			'lterm' => 36,
			'item' => 43,
			'ident' => 101
		}
	},
	{#State 18
		DEFAULT => -128
	},
	{#State 19
		DEFAULT => -26
	},
	{#State 20
		ACTIONS => {
			";" => 108
		}
	},
	{#State 21
		DEFAULT => -45
	},
	{#State 22
		DEFAULT => -131
	},
	{#State 23
		ACTIONS => {
			"\$" => 29,
			"\${" => 63,
			'LITERAL' => 111,
			'IDENT' => 22
		},
		GOTOS => {
			'ident' => 110,
			'item' => 43,
			'setlist' => 109,
			'assign' => 69,
			'node' => 18
		}
	},
	{#State 24
		DEFAULT => -9
	},
	{#State 25
		DEFAULT => -23
	},
	{#State 26
		ACTIONS => {
			'WHILE' => 117,
			'WRAPPER' => 112,
			'FILTER' => 113,
			'UNLESS' => 116,
			'FOR' => 114,
			'IF' => 115
		}
	},
	{#State 27
		ACTIONS => {
			"+" => 123,
			'CAT' => 118,
			"/" => 127,
			'DIV' => 122,
			"?" => 126,
			'MOD' => 125,
			'AND' => 121,
			'OR' => 120,
			'CMPOP' => 124,
			";" => -17,
			'BINOP' => 119
		},
		DEFAULT => -28
	},
	{#State 28
		DEFAULT => -16
	},
	{#State 29
		ACTIONS => {
			'IDENT' => 128
		}
	},
	{#State 30
		DEFAULT => -177,
		GOTOS => {
			'quoted' => 129
		}
	},
	{#State 31
		ACTIONS => {
			'IDENT' => 88,
			"\${" => 63,
			'LITERAL' => 92,
			"\"" => 89,
			"\$" => 90,
			'FILENAME' => 86,
			'NUMBER' => 84
		},
		GOTOS => {
			'item' => 94,
			'lvalue' => 93,
			'filepart' => 81,
			'filename' => 82,
			'name' => 85,
			'lnameargs' => 130,
			'names' => 83,
			'nameargs' => 95
		}
	},
	{#State 32
		ACTIONS => {
			"[" => 52,
			'LITERAL' => 102,
			'IDENT' => 22,
			'REF' => 1,
			'NUMBER' => 47,
			"{" => 75,
			"(" => 74,
			"\"" => 30,
			"\$" => 29,
			"\${" => 63,
			'NOT' => 37
		},
		GOTOS => {
			'item' => 43,
			'ident' => 101,
			'term' => 41,
			'node' => 18,
			'sterm' => 55,
			'lterm' => 36,
			'expr' => 131
		}
	},
	{#State 33
		DEFAULT => -25
	},
	{#State 34
		ACTIONS => {
			'ASSIGN' => 132
		},
		DEFAULT => -113
	},
	{#State 35
		DEFAULT => -6
	},
	{#State 36
		DEFAULT => -104
	},
	{#State 37
		ACTIONS => {
			'NUMBER' => 47,
			"{" => 75,
			"(" => 74,
			"\"" => 30,
			"\$" => 29,
			"\${" => 63,
			'NOT' => 37,
			"[" => 52,
			'LITERAL' => 102,
			'IDENT' => 22,
			'REF' => 1
		},
		GOTOS => {
			'expr' => 133,
			'lterm' => 36,
			'node' => 18,
			'sterm' => 55,
			'term' => 41,
			'ident' => 101,
			'item' => 43
		}
	},
	{#State 38
		DEFAULT => -1
	},
	{#State 39
		ACTIONS => {
			"\"" => 78,
			'FILENAME' => 86,
			"\$" => 77,
			'NUMBER' => 84,
			'IDENT' => 79,
			'LITERAL' => 80
		},
		GOTOS => {
			'filename' => 82,
			'name' => 85,
			'filepart' => 81,
			'nameargs' => 134,
			'names' => 83
		}
	},
	{#State 40
		DEFAULT => -44
	},
	{#State 41
		DEFAULT => -147
	},
	{#State 42
		ACTIONS => {
			'IDENT' => 22,
			"\${" => 63,
			'LITERAL' => 111,
			"\$" => 29
		},
		GOTOS => {
			'ident' => 110,
			'setlist' => 135,
			'item' => 43,
			'assign' => 69,
			'node' => 18
		}
	},
	{#State 43
		ACTIONS => {
			"(" => 136
		},
		DEFAULT => -129
	},
	{#State 44
		ACTIONS => {
			"[" => 52,
			'LITERAL' => 102,
			'IDENT' => 138,
			'REF' => 1,
			"{" => 75,
			'NUMBER' => 47,
			"\"" => 30,
			"\$" => 29,
			"\${" => 63
		},
		GOTOS => {
			'ident' => 101,
			'item' => 43,
			'lterm' => 36,
			'term' => 139,
			'sterm' => 55,
			'node' => 18,
			'loopvar' => 137
		}
	},
	{#State 45
		ACTIONS => {
			"\${" => 63,
			'NOT' => 37,
			"(" => 74,
			'NUMBER' => 47,
			"{" => 75,
			"\$" => 29,
			"\"" => 30,
			'LITERAL' => 102,
			'REF' => 1,
			'IDENT' => 22,
			"[" => 52
		},
		GOTOS => {
			'expr' => 140,
			'item' => 43,
			'ident' => 101,
			'sterm' => 55,
			'node' => 18,
			'term' => 41,
			'lterm' => 36
		}
	},
	{#State 46
		DEFAULT => -38
	},
	{#State 47
		DEFAULT => -114
	},
	{#State 48
		DEFAULT => -27
	},
	{#State 49
		DEFAULT => -40
	},
	{#State 50
		DEFAULT => -22
	},
	{#State 51
		ACTIONS => {
			'IDENT' => 22,
			'LITERAL' => 111,
			"\${" => 63,
			'COMMA' => 142,
			"\$" => 29
		},
		DEFAULT => -20,
		GOTOS => {
			'ident' => 110,
			'item' => 43,
			'assign' => 141,
			'node' => 18
		}
	},
	{#State 52
		ACTIONS => {
			"\"" => 30,
			"\$" => 29,
			'NUMBER' => 47,
			"{" => 75,
			"]" => 144,
			"\${" => 63,
			"[" => 52,
			'IDENT' => 22,
			'REF' => 1,
			'LITERAL' => 102
		},
		GOTOS => {
			'list' => 143,
			'lterm' => 36,
			'sterm' => 145,
			'node' => 18,
			'item' => 43,
			'range' => 147,
			'term' => 146,
			'ident' => 101
		}
	},
	{#State 53
		ACTIONS => {
			"\$" => 90,
			'FILENAME' => 86,
			"\"" => 89,
			'NUMBER' => 84,
			'IDENT' => 88,
			'LITERAL' => 92,
			"\${" => 63
		},
		GOTOS => {
			'nameargs' => 95,
			'names' => 83,
			'lnameargs' => 148,
			'name' => 85,
			'filename' => 82,
			'filepart' => 81,
			'item' => 94,
			'lvalue' => 93
		}
	},
	{#State 54
		ACTIONS => {
			'IDENT' => 100
		},
		GOTOS => {
			'metadata' => 149,
			'meta' => 97
		}
	},
	{#State 55
		DEFAULT => -105
	},
	{#State 56
		ACTIONS => {
			'DOT' => 151,
			'ASSIGN' => 150
		},
		DEFAULT => -110
	},
	{#State 57
		ACTIONS => {
			'NUMBER' => 84,
			"\"" => 78,
			'FILENAME' => 86,
			"\$" => 77,
			'LITERAL' => 80,
			'IDENT' => 79
		},
		GOTOS => {
			'names' => 83,
			'nameargs' => 152,
			'name' => 85,
			'filename' => 82,
			'filepart' => 81
		}
	},
	{#State 58
		ACTIONS => {
			";" => 153
		}
	},
	{#State 59
		ACTIONS => {
			";" => 154
		}
	},
	{#State 60
		DEFAULT => -12
	},
	{#State 61
		ACTIONS => {
			"\$" => 77,
			'FILENAME' => 86,
			"\"" => 78,
			'NUMBER' => 84,
			'IDENT' => 79,
			'LITERAL' => 80
		},
		GOTOS => {
			'names' => 83,
			'name' => 85,
			'filename' => 82,
			'filepart' => 81,
			'nameargs' => 155
		}
	},
	{#State 62
		ACTIONS => {
			"\"" => 78,
			'FILENAME' => 86,
			"\$" => 77,
			'NUMBER' => 84,
			'IDENT' => 79,
			'LITERAL' => 80
		},
		GOTOS => {
			'names' => 83,
			'nameargs' => 156,
			'filepart' => 81,
			'filename' => 82,
			'name' => 85
		}
	},
	{#State 63
		ACTIONS => {
			'REF' => 1,
			'IDENT' => 22,
			"\${" => 63,
			'LITERAL' => 102,
			"\$" => 29,
			"\"" => 30,
			'NUMBER' => 47
		},
		GOTOS => {
			'item' => 43,
			'ident' => 101,
			'node' => 18,
			'sterm' => 157
		}
	},
	{#State 64
		DEFAULT => -14
	},
	{#State 65
		ACTIONS => {
			'FILENAME' => 86,
			"\$" => 77,
			"\"" => 78,
			'NUMBER' => 84,
			'IDENT' => 79,
			'LITERAL' => 80
		},
		GOTOS => {
			'names' => 83,
			'filepart' => 81,
			'name' => 85,
			'filename' => 82,
			'nameargs' => 158
		}
	},
	{#State 66
		ACTIONS => {
			"\${" => 63,
			'NOT' => 37,
			"(" => 74,
			"{" => 75,
			'NUMBER' => 47,
			"\$" => 29,
			"\"" => 30,
			'LITERAL' => 102,
			'REF' => 1,
			'IDENT' => 22,
			"[" => 52
		},
		GOTOS => {
			'expr' => 159,
			'lterm' => 36,
			'term' => 41,
			'sterm' => 55,
			'node' => 18,
			'ident' => 101,
			'item' => 43
		}
	},
	{#State 67
		ACTIONS => {
			'IDENT' => 160
		}
	},
	{#State 68
		DEFAULT => -5
	},
	{#State 69
		DEFAULT => -150
	},
	{#State 70
		ACTIONS => {
			";" => -21
		},
		DEFAULT => -29
	},
	{#State 71
		ACTIONS => {
			'LITERAL' => 164,
			'IDENT' => 163,
			'NUMBER' => 84,
			'FILENAME' => 86
		},
		DEFAULT => -88,
		GOTOS => {
			'filename' => 165,
			'filepart' => 81,
			'blockname' => 162,
			'meta' => 97,
			'metadata' => 98,
			'blockargs' => 161
		}
	},
	{#State 72
		DEFAULT => -13
	},
	{#State 73
		DEFAULT => -8
	},
	{#State 74
		ACTIONS => {
			'LITERAL' => 34,
			'IDENT' => 22,
			'REF' => 1,
			"[" => 52,
			"\${" => 63,
			'NOT' => 37,
			'NUMBER' => 47,
			"{" => 75,
			"(" => 74,
			"\"" => 30,
			"\$" => 29
		},
		GOTOS => {
			'expr' => 168,
			'term' => 41,
			'ident' => 167,
			'node' => 18,
			'sterm' => 55,
			'lterm' => 36,
			'assign' => 166,
			'item' => 43
		}
	},
	{#State 75
		ACTIONS => {
			"\$" => 29,
			'IDENT' => 22,
			"\${" => 63,
			'LITERAL' => 171
		},
		DEFAULT => -120,
		GOTOS => {
			'param' => 169,
			'params' => 170,
			'item' => 172,
			'hash' => 173
		}
	},
	{#State 76
		ACTIONS => {
			'DOT' => 151
		},
		DEFAULT => -111
	},
	{#State 77
		ACTIONS => {
			"\$" => 29,
			"\${" => 63,
			'IDENT' => 22
		},
		GOTOS => {
			'node' => 18,
			'ident' => 174,
			'item' => 43
		}
	},
	{#State 78
		DEFAULT => -177,
		GOTOS => {
			'quoted' => 175
		}
	},
	{#State 79
		DEFAULT => -174
	},
	{#State 80
		DEFAULT => -170
	},
	{#State 81
		DEFAULT => -172
	},
	{#State 82
		ACTIONS => {
			'DOT' => 176
		},
		DEFAULT => -169
	},
	{#State 83
		ACTIONS => {
			"(" => 178,
			"+" => 177
		},
		DEFAULT => -157,
		GOTOS => {
			'args' => 179
		}
	},
	{#State 84
		DEFAULT => -175
	},
	{#State 85
		DEFAULT => -167
	},
	{#State 86
		DEFAULT => -173
	},
	{#State 87
		DEFAULT => -43
	},
	{#State 88
		ACTIONS => {
			'ASSIGN' => -131
		},
		DEFAULT => -174
	},
	{#State 89
		DEFAULT => -177,
		GOTOS => {
			'quoted' => 180
		}
	},
	{#State 90
		ACTIONS => {
			"\$" => 29,
			'IDENT' => 181,
			"\${" => 63
		},
		GOTOS => {
			'node' => 18,
			'item' => 43,
			'ident' => 174
		}
	},
	{#State 91
		DEFAULT => -75
	},
	{#State 92
		ACTIONS => {
			'ASSIGN' => -162
		},
		DEFAULT => -170
	},
	{#State 93
		ACTIONS => {
			'ASSIGN' => 182
		}
	},
	{#State 94
		DEFAULT => -160
	},
	{#State 95
		DEFAULT => -159
	},
	{#State 96
		DEFAULT => 0
	},
	{#State 97
		DEFAULT => -100
	},
	{#State 98
		ACTIONS => {
			'IDENT' => 100,
			'COMMA' => 183
		},
		DEFAULT => -87,
		GOTOS => {
			'meta' => 184
		}
	},
	{#State 99
		ACTIONS => {
			";" => 185
		}
	},
	{#State 100
		ACTIONS => {
			'ASSIGN' => 186
		}
	},
	{#State 101
		ACTIONS => {
			'DOT' => 151
		},
		DEFAULT => -110
	},
	{#State 102
		DEFAULT => -113
	},
	{#State 103
		ACTIONS => {
			'BINOP' => 119,
			'MOD' => 125,
			'OR' => 120,
			";" => 187,
			'CMPOP' => 124,
			'AND' => 121,
			'DIV' => 122,
			"?" => 126,
			"/" => 127,
			'CAT' => 118,
			"+" => 123
		}
	},
	{#State 104
		ACTIONS => {
			'BINOP' => 119,
			'MOD' => 125,
			'OR' => 120,
			";" => 188,
			'CMPOP' => 124,
			'AND' => 121,
			'DIV' => 122,
			"?" => 126,
			'CAT' => 118,
			"/" => 127,
			"+" => 123
		}
	},
	{#State 105
		DEFAULT => -4
	},
	{#State 106
		DEFAULT => -37
	},
	{#State 107
		ACTIONS => {
			'OR' => 120,
			'MOD' => 125,
			'CMPOP' => 124,
			";" => 189,
			'BINOP' => 119,
			"+" => 123,
			"/" => 127,
			'CAT' => 118,
			'AND' => 121,
			'DIV' => 122,
			"?" => 126
		}
	},
	{#State 108
		ACTIONS => {
			'WHILE' => 12,
			'CLEAR' => 49,
			'META' => 54,
			"[" => 52,
			'THROW' => 16,
			'UNLESS' => 17,
			'FILTER' => 53,
			'TRY' => 20,
			";" => -19,
			'JAVASCRIPT' => 58,
			'WRAPPER' => 57,
			'DEBUG' => 2,
			'REF' => 1,
			'DEFAULT' => 42,
			'FOR' => 44,
			'NEXT' => 4,
			'USE' => 5,
			'STOP' => 3,
			'LAST' => 9,
			'RETURN' => 46,
			'GET' => 45,
			'SWITCH' => 8,
			'perl' => 48,
			'NUMBER' => 47,
			'LITERAL' => 34,
			'MACRO' => 67,
			'TEXT' => 35,
			'NOT' => 37,
			'BLOCK' => 71,
			"{" => 75,
			"(" => 74,
			'PROCESS' => 39,
			'SET' => 23,
			'INCLUDE' => 62,
			'IDENT' => 22,
			'VIEW' => 61,
			'rawperl' => 28,
			"\${" => 63,
			'IF' => 32,
			'RAW' => 31,
			'INSERT' => 65,
			'CALL' => 66,
			"\"" => 30,
			"\$" => 29
		},
		DEFAULT => -3,
		GOTOS => {
			'sterm' => 55,
			'node' => 18,
			'assign' => 69,
			'capture' => 15,
			'lterm' => 36,
			'setlist' => 51,
			'chunk' => 68,
			'loop' => 14,
			'chunks' => 13,
			'condition' => 50,
			'view' => 11,
			'macro' => 60,
			'filter' => 21,
			'term' => 41,
			'statement' => 59,
			'wrapper' => 40,
			'directive' => 73,
			'ident' => 56,
			'block' => 190,
			'use' => 72,
			'javascript' => 19,
			'atomdir' => 70,
			'defblock' => 24,
			'defblockname' => 7,
			'switch' => 25,
			'item' => 43,
			'try' => 33,
			'anonblock' => 10,
			'raw' => 64,
			'expr' => 27,
			'atomexpr' => 26
		}
	},
	{#State 109
		ACTIONS => {
			"\$" => 29,
			"\${" => 63,
			'COMMA' => 142,
			'IDENT' => 22,
			'LITERAL' => 111
		},
		DEFAULT => -32,
		GOTOS => {
			'ident' => 110,
			'item' => 43,
			'assign' => 141,
			'node' => 18
		}
	},
	{#State 110
		ACTIONS => {
			'DOT' => 151,
			'ASSIGN' => 191
		}
	},
	{#State 111
		ACTIONS => {
			'ASSIGN' => 132
		}
	},
	{#State 112
		ACTIONS => {
			"\"" => 78,
			'FILENAME' => 86,
			"\$" => 77,
			'NUMBER' => 84,
			'IDENT' => 79,
			'LITERAL' => 80
		},
		GOTOS => {
			'names' => 83,
			'nameargs' => 192,
			'filename' => 82,
			'name' => 85,
			'filepart' => 81
		}
	},
	{#State 113
		ACTIONS => {
			"\$" => 90,
			'FILENAME' => 86,
			"\"" => 89,
			'NUMBER' => 84,
			'IDENT' => 88,
			'LITERAL' => 92,
			"\${" => 63
		},
		GOTOS => {
			'item' => 94,
			'lvalue' => 93,
			'filename' => 82,
			'name' => 85,
			'filepart' => 81,
			'lnameargs' => 193,
			'names' => 83,
			'nameargs' => 95
		}
	},
	{#State 114
		ACTIONS => {
			"\${" => 63,
			"\$" => 29,
			"\"" => 30,
			'NUMBER' => 47,
			"{" => 75,
			'REF' => 1,
			'IDENT' => 138,
			'LITERAL' => 102,
			"[" => 52
		},
		GOTOS => {
			'item' => 43,
			'ident' => 101,
			'term' => 139,
			'sterm' => 55,
			'node' => 18,
			'lterm' => 36,
			'loopvar' => 194
		}
	},
	{#State 115
		ACTIONS => {
			"[" => 52,
			'IDENT' => 22,
			'REF' => 1,
			'LITERAL' => 102,
			"\"" => 30,
			"\$" => 29,
			"{" => 75,
			'NUMBER' => 47,
			"(" => 74,
			'NOT' => 37,
			"\${" => 63
		},
		GOTOS => {
			'item' => 43,
			'ident' => 101,
			'sterm' => 55,
			'node' => 18,
			'term' => 41,
			'lterm' => 36,
			'expr' => 195
		}
	},
	{#State 116
		ACTIONS => {
			'LITERAL' => 102,
			'REF' => 1,
			'IDENT' => 22,
			"[" => 52,
			"\${" => 63,
			'NOT' => 37,
			"(" => 74,
			'NUMBER' => 47,
			"{" => 75,
			"\$" => 29,
			"\"" => 30
		},
		GOTOS => {
			'lterm' => 36,
			'node' => 18,
			'term' => 41,
			'sterm' => 55,
			'ident' => 101,
			'item' => 43,
			'expr' => 196
		}
	},
	{#State 117
		ACTIONS => {
			"[" => 52,
			'LITERAL' => 102,
			'REF' => 1,
			'IDENT' => 22,
			"(" => 74,
			'NUMBER' => 47,
			"{" => 75,
			"\$" => 29,
			"\"" => 30,
			"\${" => 63,
			'NOT' => 37
		},
		GOTOS => {
			'expr' => 197,
			'lterm' => 36,
			'sterm' => 55,
			'node' => 18,
			'term' => 41,
			'ident' => 101,
			'item' => 43
		}
	},
	{#State 118
		ACTIONS => {
			'REF' => 1,
			'IDENT' => 22,
			'LITERAL' => 102,
			"[" => 52,
			'NOT' => 37,
			"\${" => 63,
			"\$" => 29,
			"\"" => 30,
			"(" => 74,
			"{" => 75,
			'NUMBER' => 47
		},
		GOTOS => {
			'expr' => 198,
			'item' => 43,
			'ident' => 101,
			'term' => 41,
			'sterm' => 55,
			'node' => 18,
			'lterm' => 36
		}
	},
	{#State 119
		ACTIONS => {
			'IDENT' => 22,
			'REF' => 1,
			'LITERAL' => 102,
			"[" => 52,
			'NOT' => 37,
			"\${" => 63,
			"\"" => 30,
			"\$" => 29,
			'NUMBER' => 47,
			"{" => 75,
			"(" => 74
		},
		GOTOS => {
			'term' => 41,
			'node' => 18,
			'sterm' => 55,
			'lterm' => 36,
			'item' => 43,
			'ident' => 101,
			'expr' => 199
		}
	},
	{#State 120
		ACTIONS => {
			"(" => 74,
			'NUMBER' => 47,
			"{" => 75,
			"\$" => 29,
			"\"" => 30,
			"\${" => 63,
			'NOT' => 37,
			"[" => 52,
			'LITERAL' => 102,
			'REF' => 1,
			'IDENT' => 22
		},
		GOTOS => {
			'expr' => 200,
			'ident' => 101,
			'item' => 43,
			'lterm' => 36,
			'term' => 41,
			'sterm' => 55,
			'node' => 18
		}
	},
	{#State 121
		ACTIONS => {
			'IDENT' => 22,
			'REF' => 1,
			'LITERAL' => 102,
			"[" => 52,
			'NOT' => 37,
			"\${" => 63,
			"\"" => 30,
			"\$" => 29,
			"{" => 75,
			'NUMBER' => 47,
			"(" => 74
		},
		GOTOS => {
			'sterm' => 55,
			'term' => 41,
			'node' => 18,
			'lterm' => 36,
			'item' => 43,
			'ident' => 101,
			'expr' => 201
		}
	},
	{#State 122
		ACTIONS => {
			"[" => 52,
			'REF' => 1,
			'IDENT' => 22,
			'LITERAL' => 102,
			"\$" => 29,
			"\"" => 30,
			"(" => 74,
			"{" => 75,
			'NUMBER' => 47,
			'NOT' => 37,
			"\${" => 63
		},
		GOTOS => {
			'ident' => 101,
			'item' => 43,
			'lterm' => 36,
			'term' => 41,
			'sterm' => 55,
			'node' => 18,
			'expr' => 202
		}
	},
	{#State 123
		ACTIONS => {
			"\${" => 63,
			'NOT' => 37,
			"(" => 74,
			"{" => 75,
			'NUMBER' => 47,
			"\$" => 29,
			"\"" => 30,
			'LITERAL' => 102,
			'REF' => 1,
			'IDENT' => 22,
			"[" => 52
		},
		GOTOS => {
			'expr' => 203,
			'node' => 18,
			'sterm' => 55,
			'term' => 41,
			'lterm' => 36,
			'item' => 43,
			'ident' => 101
		}
	},
	{#State 124
		ACTIONS => {
			'NUMBER' => 47,
			"{" => 75,
			"(" => 74,
			"\"" => 30,
			"\$" => 29,
			"\${" => 63,
			'NOT' => 37,
			"[" => 52,
			'LITERAL' => 102,
			'IDENT' => 22,
			'REF' => 1
		},
		GOTOS => {
			'lterm' => 36,
			'sterm' => 55,
			'term' => 41,
			'node' => 18,
			'ident' => 101,
			'item' => 43,
			'expr' => 204
		}
	},
	{#State 125
		ACTIONS => {
			'IDENT' => 22,
			'REF' => 1,
			'LITERAL' => 102,
			"[" => 52,
			'NOT' => 37,
			"\${" => 63,
			"\"" => 30,
			"\$" => 29,
			'NUMBER' => 47,
			"{" => 75,
			"(" => 74
		},
		GOTOS => {
			'expr' => 205,
			'item' => 43,
			'ident' => 101,
			'node' => 18,
			'term' => 41,
			'sterm' => 55,
			'lterm' => 36
		}
	},
	{#State 126
		ACTIONS => {
			'LITERAL' => 102,
			'REF' => 1,
			'IDENT' => 22,
			"[" => 52,
			"\${" => 63,
			'NOT' => 37,
			"(" => 74,
			'NUMBER' => 47,
			"{" => 75,
			"\$" => 29,
			"\"" => 30
		},
		GOTOS => {
			'expr' => 206,
			'node' => 18,
			'sterm' => 55,
			'term' => 41,
			'lterm' => 36,
			'item' => 43,
			'ident' => 101
		}
	},
	{#State 127
		ACTIONS => {
			'LITERAL' => 102,
			'REF' => 1,
			'IDENT' => 22,
			"[" => 52,
			"\${" => 63,
			'NOT' => 37,
			"(" => 74,
			'NUMBER' => 47,
			"{" => 75,
			"\$" => 29,
			"\"" => 30
		},
		GOTOS => {
			'node' => 18,
			'term' => 41,
			'sterm' => 55,
			'lterm' => 36,
			'item' => 43,
			'ident' => 101,
			'expr' => 207
		}
	},
	{#State 128
		DEFAULT => -133
	},
	{#State 129
		ACTIONS => {
			"\${" => 63,
			'IDENT' => 22,
			";" => 211,
			'TEXT' => 208,
			"\"" => 209,
			"\$" => 29
		},
		GOTOS => {
			'node' => 18,
			'ident' => 210,
			'quotable' => 212,
			'item' => 43
		}
	},
	{#State 130
		DEFAULT => -76
	},
	{#State 131
		ACTIONS => {
			'DIV' => 122,
			'AND' => 121,
			"?" => 126,
			"/" => 127,
			'CAT' => 118,
			"+" => 123,
			'BINOP' => 119,
			'MOD' => 125,
			'OR' => 120,
			";" => 213,
			'CMPOP' => 124
		}
	},
	{#State 132
		ACTIONS => {
			"(" => 74,
			"{" => 75,
			'NUMBER' => 47,
			"\$" => 29,
			"\"" => 30,
			"\${" => 63,
			'NOT' => 37,
			"[" => 52,
			'LITERAL' => 102,
			'REF' => 1,
			'IDENT' => 22
		},
		GOTOS => {
			'item' => 43,
			'ident' => 101,
			'node' => 18,
			'sterm' => 55,
			'term' => 41,
			'lterm' => 36,
			'expr' => 214
		}
	},
	{#State 133
		ACTIONS => {
			'BINOP' => 119,
			'CMPOP' => 124,
			"+" => 123,
			'CAT' => 118,
			'DIV' => 122,
			"/" => 127,
			'MOD' => 125
		},
		DEFAULT => -143
	},
	{#State 134
		DEFAULT => -36
	},
	{#State 135
		ACTIONS => {
			'IDENT' => 22,
			'LITERAL' => 111,
			'COMMA' => 142,
			"\${" => 63,
			"\$" => 29
		},
		DEFAULT => -33,
		GOTOS => {
			'node' => 18,
			'assign' => 141,
			'item' => 43,
			'ident' => 110
		}
	},
	{#State 136
		DEFAULT => -157,
		GOTOS => {
			'args' => 215
		}
	},
	{#State 137
		ACTIONS => {
			";" => 216
		}
	},
	{#State 138
		ACTIONS => {
			'ASSIGN' => 217,
			'IN' => 218
		},
		DEFAULT => -131
	},
	{#State 139
		DEFAULT => -157,
		GOTOS => {
			'args' => 219
		}
	},
	{#State 140
		ACTIONS => {
			"+" => 123,
			"/" => 127,
			'CAT' => 118,
			"?" => 126,
			'DIV' => 122,
			'MOD' => 125,
			'AND' => 121,
			'CMPOP' => 124,
			'OR' => 120,
			'BINOP' => 119
		},
		DEFAULT => -30
	},
	{#State 141
		DEFAULT => -148
	},
	{#State 142
		DEFAULT => -149
	},
	{#State 143
		ACTIONS => {
			"\$" => 29,
			"\"" => 30,
			"]" => 220,
			'NUMBER' => 47,
			"{" => 75,
			"\${" => 63,
			'COMMA' => 221,
			"[" => 52,
			'REF' => 1,
			'IDENT' => 22,
			'LITERAL' => 102
		},
		GOTOS => {
			'lterm' => 36,
			'node' => 18,
			'term' => 222,
			'sterm' => 55,
			'ident' => 101,
			'item' => 43
		}
	},
	{#State 144
		DEFAULT => -108
	},
	{#State 145
		ACTIONS => {
			'TO' => 223
		},
		DEFAULT => -105
	},
	{#State 146
		DEFAULT => -117
	},
	{#State 147
		ACTIONS => {
			"]" => 224
		}
	},
	{#State 148
		ACTIONS => {
			";" => 225
		}
	},
	{#State 149
		ACTIONS => {
			'IDENT' => 100,
			'COMMA' => 183
		},
		DEFAULT => -18,
		GOTOS => {
			'meta' => 184
		}
	},
	{#State 150
		ACTIONS => {
			'NOT' => 37,
			'BLOCK' => 228,
			'PROCESS' => 39,
			"{" => 75,
			"(" => 74,
			'LITERAL' => 34,
			"\${" => 63,
			"\"" => 30,
			"\$" => 29,
			'IF' => 32,
			'INSERT' => 65,
			'CALL' => 66,
			'IDENT' => 22,
			'INCLUDE' => 62,
			'SET' => 23,
			'TRY' => 20,
			'WRAPPER' => 57,
			'JAVASCRIPT' => 58,
			'WHILE' => 12,
			'CLEAR' => 49,
			'THROW' => 16,
			'FILTER' => 53,
			"[" => 52,
			'UNLESS' => 17,
			'RETURN' => 46,
			'GET' => 45,
			'SWITCH' => 8,
			'LAST' => 9,
			'NUMBER' => 47,
			'perl' => 48,
			'DEFAULT' => 42,
			'REF' => 1,
			'DEBUG' => 2,
			'NEXT' => 4,
			'STOP' => 3,
			'FOR' => 44
		},
		GOTOS => {
			'mdir' => 227,
			'switch' => 25,
			'item' => 43,
			'try' => 33,
			'expr' => 226,
			'atomexpr' => 26,
			'sterm' => 55,
			'node' => 18,
			'assign' => 69,
			'lterm' => 36,
			'setlist' => 51,
			'loop' => 14,
			'condition' => 50,
			'term' => 41,
			'filter' => 21,
			'wrapper' => 40,
			'directive' => 229,
			'ident' => 167,
			'atomdir' => 70,
			'javascript' => 19
		}
	},
	{#State 151
		ACTIONS => {
			"\${" => 63,
			'IDENT' => 22,
			'NUMBER' => 231,
			"\$" => 29
		},
		GOTOS => {
			'node' => 230,
			'item' => 43
		}
	},
	{#State 152
		ACTIONS => {
			";" => 232
		}
	},
	{#State 153
		DEFAULT => -79,
		GOTOS => {
			'@4-2' => 233
		}
	},
	{#State 154
		DEFAULT => -7
	},
	{#State 155
		ACTIONS => {
			";" => 234
		}
	},
	{#State 156
		DEFAULT => -35
	},
	{#State 157
		ACTIONS => {
			"}" => 235
		}
	},
	{#State 158
		DEFAULT => -34
	},
	{#State 159
		ACTIONS => {
			'MOD' => 125,
			"/" => 127,
			'CAT' => 118,
			"+" => 123,
			'DIV' => 122,
			"?" => 126,
			'OR' => 120,
			'CMPOP' => 124,
			'BINOP' => 119,
			'AND' => 121
		},
		DEFAULT => -31
	},
	{#State 160
		ACTIONS => {
			'LAST' => 9,
			'RETURN' => 46,
			'GET' => 45,
			'SWITCH' => 8,
			'perl' => 48,
			'NUMBER' => 47,
			'DEBUG' => 2,
			'DEFAULT' => 42,
			'REF' => 1,
			'FOR' => 44,
			'NEXT' => 4,
			'STOP' => 3,
			'TRY' => 20,
			'JAVASCRIPT' => 58,
			'WRAPPER' => 57,
			'WHILE' => 12,
			'CLEAR' => 49,
			"[" => 52,
			'THROW' => 16,
			'UNLESS' => 17,
			'FILTER' => 53,
			"\${" => 63,
			'IF' => 32,
			'INSERT' => 65,
			'CALL' => 66,
			"\"" => 30,
			"\$" => 29,
			'INCLUDE' => 62,
			'SET' => 23,
			'IDENT' => 22,
			'BLOCK' => 228,
			'NOT' => 37,
			"{" => 75,
			"(" => 236,
			'PROCESS' => 39,
			'LITERAL' => 34
		},
		GOTOS => {
			'try' => 33,
			'expr' => 237,
			'atomexpr' => 26,
			'mdir' => 238,
			'switch' => 25,
			'item' => 43,
			'filter' => 21,
			'term' => 41,
			'wrapper' => 40,
			'directive' => 229,
			'ident' => 167,
			'javascript' => 19,
			'atomdir' => 70,
			'sterm' => 55,
			'node' => 18,
			'lterm' => 36,
			'assign' => 69,
			'setlist' => 51,
			'loop' => 14,
			'condition' => 50
		}
	},
	{#State 161
		ACTIONS => {
			";" => 239
		}
	},
	{#State 162
		DEFAULT => -84
	},
	{#State 163
		ACTIONS => {
			'ASSIGN' => 186
		},
		DEFAULT => -174
	},
	{#State 164
		DEFAULT => -86
	},
	{#State 165
		ACTIONS => {
			'DOT' => 176
		},
		DEFAULT => -85
	},
	{#State 166
		ACTIONS => {
			")" => 240
		}
	},
	{#State 167
		ACTIONS => {
			'DOT' => 151,
			'ASSIGN' => 191
		},
		DEFAULT => -110
	},
	{#State 168
		ACTIONS => {
			'DIV' => 122,
			'AND' => 121,
			"?" => 126,
			"/" => 127,
			'CAT' => 118,
			"+" => 123,
			")" => 241,
			'BINOP' => 119,
			'MOD' => 125,
			'OR' => 120,
			'CMPOP' => 124
		}
	},
	{#State 169
		DEFAULT => -123
	},
	{#State 170
		ACTIONS => {
			'COMMA' => 242,
			"\$" => 29,
			'IDENT' => 22,
			'LITERAL' => 171,
			"\${" => 63
		},
		DEFAULT => -119,
		GOTOS => {
			'param' => 243,
			'item' => 172
		}
	},
	{#State 171
		ACTIONS => {
			'ASSIGN' => 244
		}
	},
	{#State 172
		ACTIONS => {
			'ASSIGN' => 245
		}
	},
	{#State 173
		ACTIONS => {
			"}" => 246
		}
	},
	{#State 174
		ACTIONS => {
			'DOT' => 151
		},
		DEFAULT => -157,
		GOTOS => {
			'args' => 247
		}
	},
	{#State 175
		ACTIONS => {
			"\${" => 63,
			'IDENT' => 22,
			";" => 211,
			'TEXT' => 208,
			"\"" => 248,
			"\$" => 29
		},
		GOTOS => {
			'quotable' => 212,
			'item' => 43,
			'ident' => 210,
			'node' => 18
		}
	},
	{#State 176
		ACTIONS => {
			'FILENAME' => 86,
			'NUMBER' => 84,
			'IDENT' => 79
		},
		GOTOS => {
			'filepart' => 249
		}
	},
	{#State 177
		ACTIONS => {
			'LITERAL' => 80,
			'IDENT' => 79,
			'NUMBER' => 84,
			"\"" => 78,
			'FILENAME' => 86
		},
		GOTOS => {
			'name' => 250,
			'filename' => 82,
			'filepart' => 81
		}
	},
	{#State 178
		DEFAULT => -157,
		GOTOS => {
			'args' => 251
		}
	},
	{#State 179
		ACTIONS => {
			"[" => 52,
			'LITERAL' => 256,
			"(" => 74,
			"{" => 75,
			'NOT' => 37,
			'COMMA' => 255,
			'REF' => 1,
			'IDENT' => 22,
			'NUMBER' => 47,
			"\$" => 29,
			"\"" => 30,
			"\${" => 63
		},
		DEFAULT => -164,
		GOTOS => {
			'item' => 252,
			'sterm' => 55,
			'node' => 18,
			'lterm' => 36,
			'param' => 257,
			'ident' => 253,
			'term' => 41,
			'expr' => 254
		}
	},
	{#State 180
		ACTIONS => {
			'TEXT' => 208,
			"\$" => 29,
			"\"" => 258,
			"\${" => 63,
			";" => 211,
			'IDENT' => 22
		},
		GOTOS => {
			'quotable' => 212,
			'item' => 43,
			'ident' => 210,
			'node' => 18
		}
	},
	{#State 181
		ACTIONS => {
			'ASSIGN' => -133
		},
		DEFAULT => -131
	},
	{#State 182
		ACTIONS => {
			'LITERAL' => 80,
			'IDENT' => 79,
			'NUMBER' => 84,
			"\"" => 78,
			'FILENAME' => 86,
			"\$" => 77
		},
		GOTOS => {
			'nameargs' => 259,
			'filepart' => 81,
			'filename' => 82,
			'name' => 85,
			'names' => 83
		}
	},
	{#State 183
		DEFAULT => -99
	},
	{#State 184
		DEFAULT => -98
	},
	{#State 185
		ACTIONS => {
			'TRY' => 20,
			";" => -19,
			'WRAPPER' => 57,
			'JAVASCRIPT' => 58,
			'WHILE' => 12,
			'CLEAR' => 49,
			'META' => 54,
			'FILTER' => 53,
			"[" => 52,
			'UNLESS' => 17,
			'THROW' => 16,
			'RETURN' => 46,
			'GET' => 45,
			'SWITCH' => 8,
			'LAST' => 9,
			'NUMBER' => 47,
			'perl' => 48,
			'DEFAULT' => 42,
			'REF' => 1,
			'DEBUG' => 2,
			'NEXT' => 4,
			'USE' => 5,
			'STOP' => 3,
			'FOR' => 44,
			'BLOCK' => 71,
			'NOT' => 37,
			'PROCESS' => 39,
			"{" => 75,
			"(" => 74,
			'MACRO' => 67,
			'LITERAL' => 34,
			'TEXT' => 35,
			'rawperl' => 28,
			"\${" => 63,
			"\"" => 30,
			"\$" => 29,
			'RAW' => 31,
			'IF' => 32,
			'CALL' => 66,
			'INSERT' => 65,
			'IDENT' => 22,
			'VIEW' => 61,
			'SET' => 23,
			'INCLUDE' => 62
		},
		DEFAULT => -3,
		GOTOS => {
			'chunk' => 68,
			'lterm' => 36,
			'assign' => 69,
			'use' => 72,
			'atomdir' => 70,
			'block' => 38,
			'directive' => 73,
			'term' => 41,
			'wrapper' => 40,
			'defblock' => 24,
			'switch' => 25,
			'atomexpr' => 26,
			'expr' => 27,
			'raw' => 64,
			'try' => 33,
			'view' => 11,
			'chunks' => 13,
			'condition' => 50,
			'setlist' => 51,
			'loop' => 14,
			'sterm' => 55,
			'node' => 18,
			'capture' => 15,
			'javascript' => 19,
			'ident' => 56,
			'filter' => 21,
			'statement' => 59,
			'macro' => 60,
			'item' => 43,
			'template' => 260,
			'defblockname' => 7,
			'anonblock' => 10
		}
	},
	{#State 186
		ACTIONS => {
			"\"" => 261,
			'NUMBER' => 263,
			'LITERAL' => 262
		}
	},
	{#State 187
		ACTIONS => {
			"\$" => 29,
			"\"" => 30,
			'INSERT' => 65,
			'CALL' => 66,
			'RAW' => 31,
			'IF' => 32,
			'rawperl' => 28,
			"\${" => 63,
			'VIEW' => 61,
			'IDENT' => 22,
			'SET' => 23,
			'INCLUDE' => 62,
			'PROCESS' => 39,
			"(" => 74,
			"{" => 75,
			'BLOCK' => 71,
			'NOT' => 37,
			'TEXT' => 35,
			'MACRO' => 67,
			'LITERAL' => 34,
			'perl' => 48,
			'NUMBER' => 47,
			'SWITCH' => 8,
			'GET' => 45,
			'RETURN' => 46,
			'LAST' => 9,
			'STOP' => 3,
			'USE' => 5,
			'NEXT' => 4,
			'FOR' => 44,
			'REF' => 1,
			'DEFAULT' => 42,
			'DEBUG' => 2,
			'WRAPPER' => 57,
			'JAVASCRIPT' => 58,
			";" => -19,
			'TRY' => 20,
			'FILTER' => 53,
			"[" => 52,
			'THROW' => 16,
			'UNLESS' => 17,
			'META' => 54,
			'CLEAR' => 49,
			'WHILE' => 12
		},
		DEFAULT => -3,
		GOTOS => {
			'ident' => 56,
			'directive' => 73,
			'wrapper' => 40,
			'filter' => 21,
			'statement' => 59,
			'macro' => 60,
			'term' => 41,
			'javascript' => 19,
			'atomdir' => 70,
			'use' => 72,
			'block' => 264,
			'loop' => 14,
			'chunk' => 68,
			'setlist' => 51,
			'lterm' => 36,
			'assign' => 69,
			'capture' => 15,
			'sterm' => 55,
			'node' => 18,
			'view' => 11,
			'condition' => 50,
			'chunks' => 13,
			'raw' => 64,
			'anonblock' => 10,
			'try' => 33,
			'atomexpr' => 26,
			'expr' => 27,
			'item' => 43,
			'switch' => 25,
			'defblock' => 24,
			'defblockname' => 7
		}
	},
	{#State 188
		DEFAULT => -61,
		GOTOS => {
			'@2-3' => 265
		}
	},
	{#State 189
		ACTIONS => {
			'META' => 54,
			"[" => 52,
			'FILTER' => 53,
			'UNLESS' => 17,
			'THROW' => 16,
			'WHILE' => 12,
			'CLEAR' => 49,
			'JAVASCRIPT' => 58,
			'WRAPPER' => 57,
			'TRY' => 20,
			";" => -19,
			'FOR' => 44,
			'USE' => 5,
			'NEXT' => 4,
			'STOP' => 3,
			'DEBUG' => 2,
			'REF' => 1,
			'DEFAULT' => 42,
			'NUMBER' => 47,
			'perl' => 48,
			'LAST' => 9,
			'RETURN' => 46,
			'GET' => 45,
			'SWITCH' => 8,
			'TEXT' => 35,
			'LITERAL' => 34,
			'MACRO' => 67,
			"{" => 75,
			"(" => 74,
			'PROCESS' => 39,
			'NOT' => 37,
			'BLOCK' => 71,
			'INCLUDE' => 62,
			'SET' => 23,
			'IDENT' => 22,
			'VIEW' => 61,
			'IF' => 32,
			'RAW' => 31,
			'CALL' => 66,
			'INSERT' => 65,
			"\"" => 30,
			"\$" => 29,
			"\${" => 63,
			'rawperl' => 28
		},
		DEFAULT => -3,
		GOTOS => {
			'assign' => 69,
			'lterm' => 36,
			'capture' => 15,
			'sterm' => 55,
			'node' => 18,
			'chunk' => 68,
			'loop' => 14,
			'setlist' => 51,
			'condition' => 50,
			'chunks' => 13,
			'view' => 11,
			'wrapper' => 40,
			'statement' => 59,
			'term' => 41,
			'macro' => 60,
			'filter' => 21,
			'ident' => 56,
			'directive' => 73,
			'block' => 266,
			'atomdir' => 70,
			'javascript' => 19,
			'use' => 72,
			'defblockname' => 7,
			'defblock' => 24,
			'switch' => 25,
			'item' => 43,
			'anonblock' => 10,
			'try' => 33,
			'raw' => 64,
			'expr' => 27,
			'atomexpr' => 26
		}
	},
	{#State 190
		ACTIONS => {
			'CATCH' => 269,
			'FINAL' => 268
		},
		DEFAULT => -74,
		GOTOS => {
			'final' => 267
		}
	},
	{#State 191
		ACTIONS => {
			"\${" => 63,
			'NOT' => 37,
			"{" => 75,
			'NUMBER' => 47,
			"(" => 74,
			"\"" => 30,
			"\$" => 29,
			'LITERAL' => 102,
			'IDENT' => 22,
			'REF' => 1,
			"[" => 52
		},
		GOTOS => {
			'expr' => 270,
			'lterm' => 36,
			'node' => 18,
			'sterm' => 55,
			'term' => 41,
			'ident' => 101,
			'item' => 43
		}
	},
	{#State 192
		DEFAULT => -68
	},
	{#State 193
		DEFAULT => -82
	},
	{#State 194
		DEFAULT => -60
	},
	{#State 195
		ACTIONS => {
			'MOD' => 125,
			'OR' => 120,
			'CMPOP' => 124,
			'BINOP' => 119,
			'CAT' => 118,
			"/" => 127,
			"+" => 123,
			'DIV' => 122,
			'AND' => 121,
			"?" => 126
		},
		DEFAULT => -47
	},
	{#State 196
		ACTIONS => {
			"/" => 127,
			'CAT' => 118,
			"+" => 123,
			'DIV' => 122,
			'AND' => 121,
			"?" => 126,
			'MOD' => 125,
			'OR' => 120,
			'CMPOP' => 124,
			'BINOP' => 119
		},
		DEFAULT => -49
	},
	{#State 197
		ACTIONS => {
			'CMPOP' => 124,
			'MOD' => 125,
			'OR' => 120,
			'BINOP' => 119,
			"/" => 127,
			'CAT' => 118,
			"+" => 123,
			"?" => 126,
			'AND' => 121,
			'DIV' => 122
		},
		DEFAULT => -63
	},
	{#State 198
		ACTIONS => {
			"+" => 123,
			'CMPOP' => 124,
			'BINOP' => 119,
			'MOD' => 125,
			"/" => 127,
			'DIV' => 122
		},
		DEFAULT => -140
	},
	{#State 199
		ACTIONS => {
			'MOD' => 125,
			"/" => 127,
			'DIV' => 122,
			"+" => 123
		},
		DEFAULT => -134
	},
	{#State 200
		ACTIONS => {
			"+" => 123,
			'CAT' => 118,
			'BINOP' => 119,
			'CMPOP' => 124,
			'MOD' => 125,
			'DIV' => 122,
			"/" => 127
		},
		DEFAULT => -142
	},
	{#State 201
		ACTIONS => {
			'MOD' => 125,
			"/" => 127,
			'DIV' => 122,
			"+" => 123,
			'CAT' => 118,
			'CMPOP' => 124,
			'BINOP' => 119
		},
		DEFAULT => -141
	},
	{#State 202
		ACTIONS => {
			'MOD' => 125
		},
		DEFAULT => -137
	},
	{#State 203
		ACTIONS => {
			'DIV' => 122,
			"/" => 127,
			'MOD' => 125
		},
		DEFAULT => -136
	},
	{#State 204
		ACTIONS => {
			'DIV' => 122,
			"/" => 127,
			'MOD' => 125,
			"+" => 123,
			'BINOP' => 119
		},
		DEFAULT => -139
	},
	{#State 205
		DEFAULT => -138
	},
	{#State 206
		ACTIONS => {
			'BINOP' => 119,
			'CMPOP' => 124,
			'MOD' => 125,
			":" => 271,
			'OR' => 120,
			"?" => 126,
			'AND' => 121,
			'DIV' => 122,
			'CAT' => 118,
			"/" => 127,
			"+" => 123
		}
	},
	{#State 207
		ACTIONS => {
			'MOD' => 125,
			'DIV' => 122
		},
		DEFAULT => -135
	},
	{#State 208
		DEFAULT => -179
	},
	{#State 209
		DEFAULT => -112
	},
	{#State 210
		ACTIONS => {
			'DOT' => 151
		},
		DEFAULT => -178
	},
	{#State 211
		DEFAULT => -180
	},
	{#State 212
		DEFAULT => -176
	},
	{#State 213
		ACTIONS => {
			'NOT' => 37,
			'BLOCK' => 71,
			'PROCESS' => 39,
			"(" => 74,
			"{" => 75,
			'MACRO' => 67,
			'LITERAL' => 34,
			'TEXT' => 35,
			'rawperl' => 28,
			"\${" => 63,
			"\$" => 29,
			"\"" => 30,
			'CALL' => 66,
			'INSERT' => 65,
			'RAW' => 31,
			'IF' => 32,
			'VIEW' => 61,
			'IDENT' => 22,
			'INCLUDE' => 62,
			'SET' => 23,
			";" => -19,
			'TRY' => 20,
			'WRAPPER' => 57,
			'JAVASCRIPT' => 58,
			'CLEAR' => 49,
			'WHILE' => 12,
			'FILTER' => 53,
			"[" => 52,
			'UNLESS' => 17,
			'THROW' => 16,
			'META' => 54,
			'GET' => 45,
			'SWITCH' => 8,
			'RETURN' => 46,
			'LAST' => 9,
			'perl' => 48,
			'NUMBER' => 47,
			'DEFAULT' => 42,
			'REF' => 1,
			'DEBUG' => 2,
			'STOP' => 3,
			'USE' => 5,
			'NEXT' => 4,
			'FOR' => 44
		},
		DEFAULT => -3,
		GOTOS => {
			'try' => 33,
			'anonblock' => 10,
			'raw' => 64,
			'expr' => 27,
			'atomexpr' => 26,
			'defblock' => 24,
			'defblockname' => 7,
			'switch' => 25,
			'item' => 43,
			'statement' => 59,
			'term' => 41,
			'filter' => 21,
			'macro' => 60,
			'wrapper' => 40,
			'directive' => 73,
			'ident' => 56,
			'block' => 272,
			'use' => 72,
			'javascript' => 19,
			'atomdir' => 70,
			'sterm' => 55,
			'node' => 18,
			'lterm' => 36,
			'assign' => 69,
			'capture' => 15,
			'setlist' => 51,
			'chunk' => 68,
			'loop' => 14,
			'chunks' => 13,
			'condition' => 50,
			'view' => 11
		}
	},
	{#State 214
		ACTIONS => {
			'BINOP' => 119,
			'CMPOP' => 124,
			'OR' => 120,
			'AND' => 121,
			'MOD' => 125,
			"?" => 126,
			'DIV' => 122,
			"+" => 123,
			"/" => 127,
			'CAT' => 118
		},
		DEFAULT => -152
	},
	{#State 215
		ACTIONS => {
			'NOT' => 37,
			"\${" => 63,
			"\"" => 30,
			"\$" => 29,
			")" => 273,
			"{" => 75,
			'NUMBER' => 47,
			"(" => 74,
			'IDENT' => 22,
			'REF' => 1,
			'LITERAL' => 256,
			'COMMA' => 255,
			"[" => 52
		},
		GOTOS => {
			'sterm' => 55,
			'node' => 18,
			'lterm' => 36,
			'item' => 252,
			'param' => 257,
			'term' => 41,
			'ident' => 253,
			'expr' => 254
		}
	},
	{#State 216
		DEFAULT => -58,
		GOTOS => {
			'@1-3' => 274
		}
	},
	{#State 217
		ACTIONS => {
			"\$" => 29,
			"\"" => 30,
			'NUMBER' => 47,
			"{" => 75,
			"\${" => 63,
			"[" => 52,
			'REF' => 1,
			'IDENT' => 22,
			'LITERAL' => 102
		},
		GOTOS => {
			'item' => 43,
			'ident' => 101,
			'sterm' => 55,
			'node' => 18,
			'term' => 275,
			'lterm' => 36
		}
	},
	{#State 218
		ACTIONS => {
			'LITERAL' => 102,
			'IDENT' => 22,
			'REF' => 1,
			"[" => 52,
			"\${" => 63,
			'NUMBER' => 47,
			"{" => 75,
			"\"" => 30,
			"\$" => 29
		},
		GOTOS => {
			'lterm' => 36,
			'term' => 276,
			'sterm' => 55,
			'node' => 18,
			'ident' => 101,
			'item' => 43
		}
	},
	{#State 219
		ACTIONS => {
			'NUMBER' => 47,
			"{" => 75,
			"(" => 74,
			"\"" => 30,
			"\$" => 29,
			"\${" => 63,
			'NOT' => 37,
			"[" => 52,
			'COMMA' => 255,
			'LITERAL' => 256,
			'IDENT' => 22,
			'REF' => 1
		},
		DEFAULT => -66,
		GOTOS => {
			'item' => 252,
			'sterm' => 55,
			'node' => 18,
			'lterm' => 36,
			'param' => 257,
			'ident' => 253,
			'term' => 41,
			'expr' => 254
		}
	},
	{#State 220
		DEFAULT => -106
	},
	{#State 221
		DEFAULT => -116
	},
	{#State 222
		DEFAULT => -115
	},
	{#State 223
		ACTIONS => {
			'IDENT' => 22,
			'REF' => 1,
			"\${" => 63,
			'LITERAL' => 102,
			"\"" => 30,
			"\$" => 29,
			'NUMBER' => 47
		},
		GOTOS => {
			'node' => 18,
			'sterm' => 277,
			'item' => 43,
			'ident' => 101
		}
	},
	{#State 224
		DEFAULT => -107
	},
	{#State 225
		ACTIONS => {
			'DEBUG' => 2,
			'DEFAULT' => 42,
			'REF' => 1,
			'FOR' => 44,
			'STOP' => 3,
			'NEXT' => 4,
			'USE' => 5,
			'LAST' => 9,
			'SWITCH' => 8,
			'GET' => 45,
			'RETURN' => 46,
			'perl' => 48,
			'NUMBER' => 47,
			'CLEAR' => 49,
			'WHILE' => 12,
			'THROW' => 16,
			'FILTER' => 53,
			'UNLESS' => 17,
			"[" => 52,
			'META' => 54,
			";" => -19,
			'TRY' => 20,
			'JAVASCRIPT' => 58,
			'WRAPPER' => 57,
			'INCLUDE' => 62,
			'SET' => 23,
			'VIEW' => 61,
			'IDENT' => 22,
			"\${" => 63,
			'rawperl' => 28,
			'CALL' => 66,
			'INSERT' => 65,
			'RAW' => 31,
			'IF' => 32,
			"\$" => 29,
			"\"" => 30,
			'LITERAL' => 34,
			'MACRO' => 67,
			'TEXT' => 35,
			'NOT' => 37,
			'BLOCK' => 71,
			"(" => 74,
			"{" => 75,
			'PROCESS' => 39
		},
		DEFAULT => -3,
		GOTOS => {
			'defblock' => 24,
			'defblockname' => 7,
			'switch' => 25,
			'item' => 43,
			'expr' => 27,
			'atomexpr' => 26,
			'try' => 33,
			'anonblock' => 10,
			'raw' => 64,
			'chunks' => 13,
			'condition' => 50,
			'view' => 11,
			'sterm' => 55,
			'node' => 18,
			'assign' => 69,
			'capture' => 15,
			'lterm' => 36,
			'setlist' => 51,
			'loop' => 14,
			'chunk' => 68,
			'block' => 278,
			'use' => 72,
			'javascript' => 19,
			'atomdir' => 70,
			'macro' => 60,
			'filter' => 21,
			'statement' => 59,
			'term' => 41,
			'wrapper' => 40,
			'directive' => 73,
			'ident' => 56
		}
	},
	{#State 226
		ACTIONS => {
			'AND' => 121,
			'LITERAL' => -151,
			'BINOP' => 119,
			'CMPOP' => 124,
			";" => -151,
			'OR' => 120,
			"?" => 126,
			'COMMA' => -151,
			'DIV' => 122,
			"+" => 123,
			'IDENT' => -151,
			"/" => 127,
			'CAT' => 118,
			"\$" => -151,
			"\${" => -151,
			'MOD' => 125
		},
		DEFAULT => -28
	},
	{#State 227
		DEFAULT => -90
	},
	{#State 228
		ACTIONS => {
			";" => 279
		}
	},
	{#State 229
		DEFAULT => -93
	},
	{#State 230
		DEFAULT => -126
	},
	{#State 231
		DEFAULT => -127
	},
	{#State 232
		ACTIONS => {
			'TEXT' => 35,
			'MACRO' => 67,
			'LITERAL' => 34,
			'PROCESS' => 39,
			"(" => 74,
			"{" => 75,
			'BLOCK' => 71,
			'NOT' => 37,
			'VIEW' => 61,
			'IDENT' => 22,
			'INCLUDE' => 62,
			'SET' => 23,
			"\$" => 29,
			"\"" => 30,
			'INSERT' => 65,
			'CALL' => 66,
			'RAW' => 31,
			'IF' => 32,
			'rawperl' => 28,
			"\${" => 63,
			'FILTER' => 53,
			'THROW' => 16,
			'UNLESS' => 17,
			"[" => 52,
			'META' => 54,
			'CLEAR' => 49,
			'WHILE' => 12,
			'WRAPPER' => 57,
			'JAVASCRIPT' => 58,
			";" => -19,
			'TRY' => 20,
			'STOP' => 3,
			'NEXT' => 4,
			'USE' => 5,
			'FOR' => 44,
			'REF' => 1,
			'DEFAULT' => 42,
			'DEBUG' => 2,
			'NUMBER' => 47,
			'perl' => 48,
			'GET' => 45,
			'SWITCH' => 8,
			'RETURN' => 46,
			'LAST' => 9
		},
		DEFAULT => -3,
		GOTOS => {
			'expr' => 27,
			'atomexpr' => 26,
			'anonblock' => 10,
			'try' => 33,
			'raw' => 64,
			'switch' => 25,
			'defblock' => 24,
			'defblockname' => 7,
			'item' => 43,
			'block' => 280,
			'javascript' => 19,
			'atomdir' => 70,
			'use' => 72,
			'wrapper' => 40,
			'filter' => 21,
			'term' => 41,
			'statement' => 59,
			'macro' => 60,
			'ident' => 56,
			'directive' => 73,
			'condition' => 50,
			'chunks' => 13,
			'view' => 11,
			'assign' => 69,
			'lterm' => 36,
			'capture' => 15,
			'sterm' => 55,
			'node' => 18,
			'loop' => 14,
			'chunk' => 68,
			'setlist' => 51
		}
	},
	{#State 233
		ACTIONS => {
			'STOP' => 3,
			'NEXT' => 4,
			'USE' => 5,
			'FOR' => 44,
			'DEFAULT' => 42,
			'REF' => 1,
			'DEBUG' => 2,
			'perl' => 48,
			'NUMBER' => 47,
			'SWITCH' => 8,
			'GET' => 45,
			'RETURN' => 46,
			'LAST' => 9,
			'FILTER' => 53,
			"[" => 52,
			'THROW' => 16,
			'UNLESS' => 17,
			'META' => 54,
			'CLEAR' => 49,
			'WHILE' => 12,
			'WRAPPER' => 57,
			'JAVASCRIPT' => 58,
			";" => -19,
			'TRY' => 20,
			'VIEW' => 61,
			'IDENT' => 22,
			'SET' => 23,
			'INCLUDE' => 62,
			"\$" => 29,
			"\"" => 30,
			'INSERT' => 65,
			'CALL' => 66,
			'IF' => 32,
			'RAW' => 31,
			'rawperl' => 28,
			"\${" => 63,
			'TEXT' => 35,
			'MACRO' => 67,
			'LITERAL' => 34,
			'PROCESS' => 39,
			"(" => 74,
			"{" => 75,
			'BLOCK' => 71,
			'NOT' => 37
		},
		DEFAULT => -3,
		GOTOS => {
			'atomexpr' => 26,
			'expr' => 27,
			'raw' => 64,
			'anonblock' => 10,
			'try' => 33,
			'item' => 43,
			'defblock' => 24,
			'switch' => 25,
			'defblockname' => 7,
			'javascript' => 19,
			'atomdir' => 70,
			'use' => 72,
			'block' => 281,
			'ident' => 56,
			'directive' => 73,
			'wrapper' => 40,
			'macro' => 60,
			'term' => 41,
			'statement' => 59,
			'filter' => 21,
			'view' => 11,
			'condition' => 50,
			'chunks' => 13,
			'chunk' => 68,
			'loop' => 14,
			'setlist' => 51,
			'assign' => 69,
			'lterm' => 36,
			'capture' => 15,
			'node' => 18,
			'sterm' => 55
		}
	},
	{#State 234
		DEFAULT => -77,
		GOTOS => {
			'@3-3' => 282
		}
	},
	{#State 235
		DEFAULT => -132
	},
	{#State 236
		ACTIONS => {
			"[" => 52,
			'LITERAL' => 34,
			'REF' => 1,
			'IDENT' => 283,
			"(" => 74,
			'NUMBER' => 47,
			"{" => 75,
			"\$" => 29,
			"\"" => 30,
			"\${" => 63,
			'NOT' => 37
		},
		GOTOS => {
			'margs' => 284,
			'assign' => 166,
			'lterm' => 36,
			'sterm' => 55,
			'node' => 18,
			'item' => 43,
			'expr' => 168,
			'term' => 41,
			'ident' => 167
		}
	},
	{#State 237
		ACTIONS => {
			"+" => 123,
			"/" => 127,
			'CAT' => 118,
			'DIV' => 122,
			"?" => 126,
			'MOD' => 125,
			'AND' => 121,
			'OR' => 120,
			'CMPOP' => 124,
			'BINOP' => 119
		},
		DEFAULT => -28
	},
	{#State 238
		DEFAULT => -92
	},
	{#State 239
		ACTIONS => {
			'LAST' => 9,
			'GET' => 45,
			'SWITCH' => 8,
			'RETURN' => 46,
			'perl' => 48,
			'NUMBER' => 47,
			'DEBUG' => 2,
			'REF' => 1,
			'DEFAULT' => 42,
			'FOR' => 44,
			'STOP' => 3,
			'NEXT' => 4,
			'USE' => 5,
			";" => -19,
			'TRY' => 20,
			'JAVASCRIPT' => 58,
			'WRAPPER' => 57,
			'CLEAR' => 49,
			'WHILE' => 12,
			'THROW' => 16,
			'FILTER' => 53,
			"[" => 52,
			'UNLESS' => 17,
			'META' => 54,
			"\${" => 63,
			'rawperl' => 28,
			'INSERT' => 65,
			'CALL' => 66,
			'RAW' => 31,
			'IF' => 32,
			"\$" => 29,
			"\"" => 30,
			'SET' => 23,
			'INCLUDE' => 62,
			'VIEW' => 61,
			'IDENT' => 22,
			'NOT' => 37,
			'BLOCK' => 71,
			"(" => 74,
			"{" => 75,
			'PROCESS' => 39,
			'LITERAL' => 34,
			'MACRO' => 67,
			'TEXT' => 35
		},
		DEFAULT => -3,
		GOTOS => {
			'setlist' => 51,
			'chunk' => 68,
			'loop' => 14,
			'node' => 18,
			'sterm' => 55,
			'assign' => 69,
			'lterm' => 36,
			'capture' => 15,
			'view' => 11,
			'chunks' => 13,
			'condition' => 50,
			'directive' => 73,
			'ident' => 56,
			'statement' => 59,
			'macro' => 60,
			'term' => 41,
			'filter' => 21,
			'wrapper' => 40,
			'use' => 72,
			'javascript' => 19,
			'atomdir' => 70,
			'block' => 285,
			'item' => 43,
			'switch' => 25,
			'defblockname' => 7,
			'defblock' => 24,
			'raw' => 64,
			'try' => 33,
			'anonblock' => 10,
			'atomexpr' => 26,
			'expr' => 27
		}
	},
	{#State 240
		DEFAULT => -145
	},
	{#State 241
		DEFAULT => -146
	},
	{#State 242
		DEFAULT => -122
	},
	{#State 243
		DEFAULT => -121
	},
	{#State 244
		ACTIONS => {
			"\"" => 30,
			"\$" => 29,
			'NUMBER' => 47,
			"{" => 75,
			"(" => 74,
			'NOT' => 37,
			"\${" => 63,
			"[" => 52,
			'IDENT' => 22,
			'REF' => 1,
			'LITERAL' => 102
		},
		GOTOS => {
			'ident' => 101,
			'item' => 43,
			'lterm' => 36,
			'term' => 41,
			'sterm' => 55,
			'node' => 18,
			'expr' => 286
		}
	},
	{#State 245
		ACTIONS => {
			"\${" => 63,
			'NOT' => 37,
			'NUMBER' => 47,
			"{" => 75,
			"(" => 74,
			"\"" => 30,
			"\$" => 29,
			'LITERAL' => 102,
			'IDENT' => 22,
			'REF' => 1,
			"[" => 52
		},
		GOTOS => {
			'expr' => 287,
			'item' => 43,
			'ident' => 101,
			'sterm' => 55,
			'node' => 18,
			'term' => 41,
			'lterm' => 36
		}
	},
	{#State 246
		DEFAULT => -109
	},
	{#State 247
		ACTIONS => {
			'NOT' => 37,
			"{" => 75,
			"(" => 74,
			'LITERAL' => 256,
			"[" => 52,
			"\${" => 63,
			"\"" => 30,
			"\$" => 29,
			'NUMBER' => 47,
			'IDENT' => 22,
			'REF' => 1,
			'COMMA' => 255
		},
		DEFAULT => -163,
		GOTOS => {
			'term' => 41,
			'ident' => 253,
			'expr' => 254,
			'node' => 18,
			'sterm' => 55,
			'lterm' => 36,
			'item' => 252,
			'param' => 257
		}
	},
	{#State 248
		DEFAULT => -168
	},
	{#State 249
		DEFAULT => -171
	},
	{#State 250
		DEFAULT => -166
	},
	{#State 251
		ACTIONS => {
			'NOT' => 37,
			"\${" => 63,
			"\"" => 30,
			"\$" => 29,
			")" => 288,
			"{" => 75,
			'NUMBER' => 47,
			"(" => 74,
			'IDENT' => 22,
			'REF' => 1,
			'LITERAL' => 256,
			'COMMA' => 255,
			"[" => 52
		},
		GOTOS => {
			'param' => 257,
			'lterm' => 36,
			'node' => 18,
			'sterm' => 55,
			'item' => 252,
			'expr' => 254,
			'term' => 41,
			'ident' => 253
		}
	},
	{#State 252
		ACTIONS => {
			'ASSIGN' => 245,
			"(" => 136
		},
		DEFAULT => -129
	},
	{#State 253
		ACTIONS => {
			'ASSIGN' => 289,
			'DOT' => 151
		},
		DEFAULT => -110
	},
	{#State 254
		ACTIONS => {
			"?" => 126,
			'DIV' => 122,
			"+" => 123,
			'CAT' => 118,
			"/" => 127,
			'MOD' => 125,
			'AND' => 121,
			'BINOP' => 119,
			'CMPOP' => 124,
			'OR' => 120
		},
		DEFAULT => -153
	},
	{#State 255
		DEFAULT => -156
	},
	{#State 256
		ACTIONS => {
			'ASSIGN' => 244
		},
		DEFAULT => -113
	},
	{#State 257
		DEFAULT => -154
	},
	{#State 258
		ACTIONS => {
			'ASSIGN' => -161
		},
		DEFAULT => -168
	},
	{#State 259
		DEFAULT => -158
	},
	{#State 260
		ACTIONS => {
			'END' => 290
		}
	},
	{#State 261
		ACTIONS => {
			'TEXT' => 291
		}
	},
	{#State 262
		DEFAULT => -101
	},
	{#State 263
		DEFAULT => -103
	},
	{#State 264
		ACTIONS => {
			'CASE' => 292
		},
		DEFAULT => -57,
		GOTOS => {
			'case' => 293
		}
	},
	{#State 265
		ACTIONS => {
			'rawperl' => 28,
			"\${" => 63,
			'IF' => 32,
			'RAW' => 31,
			'INSERT' => 65,
			'CALL' => 66,
			"\"" => 30,
			"\$" => 29,
			'INCLUDE' => 62,
			'SET' => 23,
			'IDENT' => 22,
			'VIEW' => 61,
			'BLOCK' => 71,
			'NOT' => 37,
			"{" => 75,
			"(" => 74,
			'PROCESS' => 39,
			'LITERAL' => 34,
			'MACRO' => 67,
			'TEXT' => 35,
			'LAST' => 9,
			'RETURN' => 46,
			'GET' => 45,
			'SWITCH' => 8,
			'perl' => 48,
			'NUMBER' => 47,
			'DEBUG' => 2,
			'REF' => 1,
			'DEFAULT' => 42,
			'FOR' => 44,
			'USE' => 5,
			'NEXT' => 4,
			'STOP' => 3,
			'TRY' => 20,
			";" => -19,
			'JAVASCRIPT' => 58,
			'WRAPPER' => 57,
			'WHILE' => 12,
			'CLEAR' => 49,
			'META' => 54,
			"[" => 52,
			'UNLESS' => 17,
			'THROW' => 16,
			'FILTER' => 53
		},
		DEFAULT => -3,
		GOTOS => {
			'ident' => 56,
			'directive' => 73,
			'wrapper' => 40,
			'filter' => 21,
			'term' => 41,
			'macro' => 60,
			'statement' => 59,
			'atomdir' => 70,
			'javascript' => 19,
			'use' => 72,
			'block' => 294,
			'chunk' => 68,
			'loop' => 14,
			'setlist' => 51,
			'lterm' => 36,
			'assign' => 69,
			'capture' => 15,
			'sterm' => 55,
			'node' => 18,
			'view' => 11,
			'condition' => 50,
			'chunks' => 13,
			'raw' => 64,
			'anonblock' => 10,
			'try' => 33,
			'atomexpr' => 26,
			'expr' => 27,
			'item' => 43,
			'switch' => 25,
			'defblock' => 24,
			'defblockname' => 7
		}
	},
	{#State 266
		ACTIONS => {
			'ELSIF' => 297,
			'ELSE' => 296
		},
		DEFAULT => -52,
		GOTOS => {
			'else' => 295
		}
	},
	{#State 267
		ACTIONS => {
			'END' => 298
		}
	},
	{#State 268
		ACTIONS => {
			";" => 299
		}
	},
	{#State 269
		ACTIONS => {
			'DEFAULT' => 301,
			";" => 300,
			'IDENT' => 79,
			'FILENAME' => 86,
			'NUMBER' => 84
		},
		GOTOS => {
			'filename' => 302,
			'filepart' => 81
		}
	},
	{#State 270
		ACTIONS => {
			'MOD' => 125,
			"?" => 126,
			'DIV' => 122,
			"/" => 127,
			'CAT' => 118,
			"+" => 123,
			'BINOP' => 119,
			'CMPOP' => 124,
			'OR' => 120,
			'AND' => 121
		},
		DEFAULT => -151
	},
	{#State 271
		ACTIONS => {
			"\"" => 30,
			"\$" => 29,
			"{" => 75,
			'NUMBER' => 47,
			"(" => 74,
			'NOT' => 37,
			"\${" => 63,
			"[" => 52,
			'IDENT' => 22,
			'REF' => 1,
			'LITERAL' => 102
		},
		GOTOS => {
			'expr' => 303,
			'node' => 18,
			'sterm' => 55,
			'term' => 41,
			'lterm' => 36,
			'item' => 43,
			'ident' => 101
		}
	},
	{#State 272
		ACTIONS => {
			'ELSIF' => 297,
			'ELSE' => 296
		},
		DEFAULT => -52,
		GOTOS => {
			'else' => 304
		}
	},
	{#State 273
		DEFAULT => -130
	},
	{#State 274
		ACTIONS => {
			'rawperl' => 28,
			"\${" => 63,
			'RAW' => 31,
			'IF' => 32,
			'CALL' => 66,
			'INSERT' => 65,
			"\"" => 30,
			"\$" => 29,
			'INCLUDE' => 62,
			'SET' => 23,
			'IDENT' => 22,
			'VIEW' => 61,
			'BLOCK' => 71,
			'NOT' => 37,
			"{" => 75,
			"(" => 74,
			'PROCESS' => 39,
			'LITERAL' => 34,
			'MACRO' => 67,
			'TEXT' => 35,
			'LAST' => 9,
			'RETURN' => 46,
			'SWITCH' => 8,
			'GET' => 45,
			'perl' => 48,
			'NUMBER' => 47,
			'DEBUG' => 2,
			'DEFAULT' => 42,
			'REF' => 1,
			'FOR' => 44,
			'NEXT' => 4,
			'USE' => 5,
			'STOP' => 3,
			'TRY' => 20,
			";" => -19,
			'JAVASCRIPT' => 58,
			'WRAPPER' => 57,
			'WHILE' => 12,
			'CLEAR' => 49,
			'META' => 54,
			"[" => 52,
			'FILTER' => 53,
			'THROW' => 16,
			'UNLESS' => 17
		},
		DEFAULT => -3,
		GOTOS => {
			'atomdir' => 70,
			'javascript' => 19,
			'use' => 72,
			'block' => 305,
			'ident' => 56,
			'directive' => 73,
			'wrapper' => 40,
			'term' => 41,
			'macro' => 60,
			'statement' => 59,
			'filter' => 21,
			'view' => 11,
			'condition' => 50,
			'chunks' => 13,
			'chunk' => 68,
			'loop' => 14,
			'setlist' => 51,
			'lterm' => 36,
			'capture' => 15,
			'assign' => 69,
			'sterm' => 55,
			'node' => 18,
			'atomexpr' => 26,
			'expr' => 27,
			'raw' => 64,
			'anonblock' => 10,
			'try' => 33,
			'item' => 43,
			'defblockname' => 7,
			'switch' => 25,
			'defblock' => 24
		}
	},
	{#State 275
		DEFAULT => -157,
		GOTOS => {
			'args' => 306
		}
	},
	{#State 276
		DEFAULT => -157,
		GOTOS => {
			'args' => 307
		}
	},
	{#State 277
		DEFAULT => -118
	},
	{#State 278
		ACTIONS => {
			'END' => 308
		}
	},
	{#State 279
		ACTIONS => {
			'WHILE' => 12,
			'CLEAR' => 49,
			'META' => 54,
			'UNLESS' => 17,
			'FILTER' => 53,
			"[" => 52,
			'THROW' => 16,
			'TRY' => 20,
			";" => -19,
			'JAVASCRIPT' => 58,
			'WRAPPER' => 57,
			'DEBUG' => 2,
			'DEFAULT' => 42,
			'REF' => 1,
			'FOR' => 44,
			'NEXT' => 4,
			'USE' => 5,
			'STOP' => 3,
			'LAST' => 9,
			'RETURN' => 46,
			'GET' => 45,
			'SWITCH' => 8,
			'NUMBER' => 47,
			'perl' => 48,
			'LITERAL' => 34,
			'MACRO' => 67,
			'TEXT' => 35,
			'BLOCK' => 71,
			'NOT' => 37,
			"{" => 75,
			"(" => 74,
			'PROCESS' => 39,
			'INCLUDE' => 62,
			'SET' => 23,
			'IDENT' => 22,
			'VIEW' => 61,
			"\${" => 63,
			'rawperl' => 28,
			'RAW' => 31,
			'IF' => 32,
			'CALL' => 66,
			'INSERT' => 65,
			"\"" => 30,
			"\$" => 29
		},
		DEFAULT => -3,
		GOTOS => {
			'anonblock' => 10,
			'try' => 33,
			'raw' => 64,
			'expr' => 27,
			'atomexpr' => 26,
			'defblock' => 24,
			'defblockname' => 7,
			'switch' => 25,
			'item' => 43,
			'wrapper' => 40,
			'term' => 41,
			'macro' => 60,
			'statement' => 59,
			'filter' => 21,
			'ident' => 56,
			'directive' => 73,
			'block' => 309,
			'javascript' => 19,
			'atomdir' => 70,
			'use' => 72,
			'assign' => 69,
			'capture' => 15,
			'lterm' => 36,
			'node' => 18,
			'sterm' => 55,
			'loop' => 14,
			'chunk' => 68,
			'setlist' => 51,
			'condition' => 50,
			'chunks' => 13,
			'view' => 11
		}
	},
	{#State 280
		ACTIONS => {
			'END' => 310
		}
	},
	{#State 281
		ACTIONS => {
			'END' => 311
		}
	},
	{#State 282
		ACTIONS => {
			'MACRO' => 67,
			'LITERAL' => 34,
			'TEXT' => 35,
			'BLOCK' => 71,
			'NOT' => 37,
			'PROCESS' => 39,
			"{" => 75,
			"(" => 74,
			'IDENT' => 22,
			'VIEW' => 61,
			'SET' => 23,
			'INCLUDE' => 62,
			'rawperl' => 28,
			"\${" => 63,
			"\"" => 30,
			"\$" => 29,
			'RAW' => 31,
			'IF' => 32,
			'INSERT' => 65,
			'CALL' => 66,
			'WHILE' => 12,
			'CLEAR' => 49,
			'META' => 54,
			'THROW' => 16,
			"[" => 52,
			'UNLESS' => 17,
			'FILTER' => 53,
			'TRY' => 20,
			";" => -19,
			'WRAPPER' => 57,
			'JAVASCRIPT' => 58,
			'REF' => 1,
			'DEFAULT' => 42,
			'DEBUG' => 2,
			'NEXT' => 4,
			'USE' => 5,
			'STOP' => 3,
			'FOR' => 44,
			'RETURN' => 46,
			'GET' => 45,
			'SWITCH' => 8,
			'LAST' => 9,
			'perl' => 48,
			'NUMBER' => 47
		},
		DEFAULT => -3,
		GOTOS => {
			'raw' => 64,
			'try' => 33,
			'anonblock' => 10,
			'atomexpr' => 26,
			'expr' => 27,
			'item' => 43,
			'defblockname' => 7,
			'switch' => 25,
			'defblock' => 24,
			'directive' => 73,
			'ident' => 56,
			'term' => 41,
			'filter' => 21,
			'macro' => 60,
			'statement' => 59,
			'wrapper' => 40,
			'use' => 72,
			'atomdir' => 70,
			'javascript' => 19,
			'block' => 312,
			'setlist' => 51,
			'loop' => 14,
			'chunk' => 68,
			'node' => 18,
			'sterm' => 55,
			'capture' => 15,
			'lterm' => 36,
			'assign' => 69,
			'view' => 11,
			'chunks' => 13,
			'condition' => 50
		}
	},
	{#State 283
		ACTIONS => {
			'COMMA' => -97,
			'IDENT' => -97,
			")" => -97
		},
		DEFAULT => -131
	},
	{#State 284
		ACTIONS => {
			'IDENT' => 315,
			'COMMA' => 314,
			")" => 313
		}
	},
	{#State 285
		ACTIONS => {
			'END' => 316
		}
	},
	{#State 286
		ACTIONS => {
			'DIV' => 122,
			"?" => 126,
			"/" => 127,
			'MOD' => 125,
			'AND' => 121,
			'BINOP' => 119,
			'OR' => 120,
			'CMPOP' => 124,
			"+" => 123,
			'CAT' => 118
		},
		DEFAULT => -124
	},
	{#State 287
		ACTIONS => {
			"+" => 123,
			'CAT' => 118,
			'AND' => 121,
			'BINOP' => 119,
			'OR' => 120,
			'CMPOP' => 124,
			'DIV' => 122,
			"?" => 126,
			"/" => 127,
			'MOD' => 125
		},
		DEFAULT => -125
	},
	{#State 288
		DEFAULT => -165
	},
	{#State 289
		ACTIONS => {
			"[" => 52,
			'LITERAL' => 102,
			'IDENT' => 22,
			'REF' => 1,
			"{" => 75,
			'NUMBER' => 47,
			"(" => 74,
			"\"" => 30,
			"\$" => 29,
			"\${" => 63,
			'NOT' => 37
		},
		GOTOS => {
			'expr' => 317,
			'item' => 43,
			'ident' => 101,
			'sterm' => 55,
			'term' => 41,
			'node' => 18,
			'lterm' => 36
		}
	},
	{#State 290
		DEFAULT => -83
	},
	{#State 291
		ACTIONS => {
			"\"" => 318
		}
	},
	{#State 292
		ACTIONS => {
			"\${" => 63,
			";" => 320,
			"{" => 75,
			'NUMBER' => 47,
			"\"" => 30,
			"\$" => 29,
			'LITERAL' => 102,
			'IDENT' => 22,
			'DEFAULT' => 321,
			'REF' => 1,
			"[" => 52
		},
		GOTOS => {
			'lterm' => 36,
			'term' => 319,
			'sterm' => 55,
			'node' => 18,
			'ident' => 101,
			'item' => 43
		}
	},
	{#State 293
		ACTIONS => {
			'END' => 322
		}
	},
	{#State 294
		ACTIONS => {
			'END' => 323
		}
	},
	{#State 295
		ACTIONS => {
			'END' => 324
		}
	},
	{#State 296
		ACTIONS => {
			";" => 325
		}
	},
	{#State 297
		ACTIONS => {
			"\${" => 63,
			'NOT' => 37,
			"(" => 74,
			"{" => 75,
			'NUMBER' => 47,
			"\$" => 29,
			"\"" => 30,
			'LITERAL' => 102,
			'REF' => 1,
			'IDENT' => 22,
			"[" => 52
		},
		GOTOS => {
			'ident' => 101,
			'item' => 43,
			'lterm' => 36,
			'term' => 41,
			'node' => 18,
			'sterm' => 55,
			'expr' => 326
		}
	},
	{#State 298
		DEFAULT => -69
	},
	{#State 299
		ACTIONS => {
			'SWITCH' => 8,
			'GET' => 45,
			'RETURN' => 46,
			'LAST' => 9,
			'perl' => 48,
			'NUMBER' => 47,
			'DEFAULT' => 42,
			'REF' => 1,
			'DEBUG' => 2,
			'STOP' => 3,
			'NEXT' => 4,
			'USE' => 5,
			'FOR' => 44,
			";" => -19,
			'TRY' => 20,
			'WRAPPER' => 57,
			'JAVASCRIPT' => 58,
			'CLEAR' => 49,
			'WHILE' => 12,
			'THROW' => 16,
			'FILTER' => 53,
			"[" => 52,
			'UNLESS' => 17,
			'META' => 54,
			"\${" => 63,
			'rawperl' => 28,
			"\$" => 29,
			"\"" => 30,
			'INSERT' => 65,
			'CALL' => 66,
			'RAW' => 31,
			'IF' => 32,
			'VIEW' => 61,
			'IDENT' => 22,
			'SET' => 23,
			'INCLUDE' => 62,
			'BLOCK' => 71,
			'NOT' => 37,
			'PROCESS' => 39,
			"(" => 74,
			"{" => 75,
			'MACRO' => 67,
			'LITERAL' => 34,
			'TEXT' => 35
		},
		DEFAULT => -3,
		GOTOS => {
			'item' => 43,
			'defblock' => 24,
			'defblockname' => 7,
			'switch' => 25,
			'raw' => 64,
			'try' => 33,
			'anonblock' => 10,
			'atomexpr' => 26,
			'expr' => 27,
			'setlist' => 51,
			'loop' => 14,
			'chunk' => 68,
			'node' => 18,
			'sterm' => 55,
			'lterm' => 36,
			'assign' => 69,
			'capture' => 15,
			'view' => 11,
			'chunks' => 13,
			'condition' => 50,
			'directive' => 73,
			'ident' => 56,
			'macro' => 60,
			'term' => 41,
			'filter' => 21,
			'statement' => 59,
			'wrapper' => 40,
			'use' => 72,
			'javascript' => 19,
			'atomdir' => 70,
			'block' => 327
		}
	},
	{#State 300
		ACTIONS => {
			'NUMBER' => 47,
			'perl' => 48,
			'LAST' => 9,
			'RETURN' => 46,
			'SWITCH' => 8,
			'GET' => 45,
			'FOR' => 44,
			'NEXT' => 4,
			'USE' => 5,
			'STOP' => 3,
			'DEBUG' => 2,
			'REF' => 1,
			'DEFAULT' => 42,
			'JAVASCRIPT' => 58,
			'WRAPPER' => 57,
			'TRY' => 20,
			";" => -19,
			'META' => 54,
			"[" => 52,
			'THROW' => 16,
			'UNLESS' => 17,
			'FILTER' => 53,
			'WHILE' => 12,
			'CLEAR' => 49,
			'RAW' => 31,
			'IF' => 32,
			'CALL' => 66,
			'INSERT' => 65,
			"\"" => 30,
			"\$" => 29,
			"\${" => 63,
			'rawperl' => 28,
			'SET' => 23,
			'INCLUDE' => 62,
			'IDENT' => 22,
			'VIEW' => 61,
			"{" => 75,
			"(" => 74,
			'PROCESS' => 39,
			'BLOCK' => 71,
			'NOT' => 37,
			'TEXT' => 35,
			'LITERAL' => 34,
			'MACRO' => 67
		},
		DEFAULT => -3,
		GOTOS => {
			'block' => 328,
			'use' => 72,
			'atomdir' => 70,
			'javascript' => 19,
			'statement' => 59,
			'filter' => 21,
			'term' => 41,
			'macro' => 60,
			'wrapper' => 40,
			'directive' => 73,
			'ident' => 56,
			'chunks' => 13,
			'condition' => 50,
			'view' => 11,
			'sterm' => 55,
			'node' => 18,
			'capture' => 15,
			'lterm' => 36,
			'assign' => 69,
			'setlist' => 51,
			'chunk' => 68,
			'loop' => 14,
			'expr' => 27,
			'atomexpr' => 26,
			'try' => 33,
			'anonblock' => 10,
			'raw' => 64,
			'defblockname' => 7,
			'defblock' => 24,
			'switch' => 25,
			'item' => 43
		}
	},
	{#State 301
		ACTIONS => {
			";" => 329
		}
	},
	{#State 302
		ACTIONS => {
			";" => 330,
			'DOT' => 176
		}
	},
	{#State 303
		ACTIONS => {
			'BINOP' => 119,
			'OR' => 120,
			'CMPOP' => 124,
			'AND' => 121,
			"+" => 123,
			'CAT' => 118,
			'MOD' => 125,
			'DIV' => 122,
			"?" => 126,
			"/" => 127
		},
		DEFAULT => -144
	},
	{#State 304
		ACTIONS => {
			'END' => 331
		}
	},
	{#State 305
		ACTIONS => {
			'END' => 332
		}
	},
	{#State 306
		ACTIONS => {
			'NUMBER' => 47,
			"{" => 75,
			"(" => 74,
			"\"" => 30,
			"\$" => 29,
			"\${" => 63,
			'NOT' => 37,
			"[" => 52,
			'COMMA' => 255,
			'LITERAL' => 256,
			'IDENT' => 22,
			'REF' => 1
		},
		DEFAULT => -64,
		GOTOS => {
			'node' => 18,
			'sterm' => 55,
			'lterm' => 36,
			'item' => 252,
			'param' => 257,
			'term' => 41,
			'ident' => 253,
			'expr' => 254
		}
	},
	{#State 307
		ACTIONS => {
			"\"" => 30,
			"\$" => 29,
			"{" => 75,
			'NUMBER' => 47,
			"(" => 74,
			'NOT' => 37,
			"\${" => 63,
			'COMMA' => 255,
			"[" => 52,
			'IDENT' => 22,
			'REF' => 1,
			'LITERAL' => 256
		},
		DEFAULT => -65,
		GOTOS => {
			'param' => 257,
			'sterm' => 55,
			'node' => 18,
			'lterm' => 36,
			'item' => 252,
			'expr' => 254,
			'term' => 41,
			'ident' => 253
		}
	},
	{#State 308
		DEFAULT => -81
	},
	{#State 309
		ACTIONS => {
			'END' => 333
		}
	},
	{#State 310
		DEFAULT => -67
	},
	{#State 311
		DEFAULT => -80
	},
	{#State 312
		ACTIONS => {
			'END' => 334
		}
	},
	{#State 313
		ACTIONS => {
			'NUMBER' => 47,
			'perl' => 48,
			'LAST' => 9,
			'RETURN' => 46,
			'SWITCH' => 8,
			'GET' => 45,
			'FOR' => 44,
			'NEXT' => 4,
			'STOP' => 3,
			'DEBUG' => 2,
			'DEFAULT' => 42,
			'REF' => 1,
			'JAVASCRIPT' => 58,
			'WRAPPER' => 57,
			'TRY' => 20,
			'UNLESS' => 17,
			'FILTER' => 53,
			"[" => 52,
			'THROW' => 16,
			'WHILE' => 12,
			'CLEAR' => 49,
			'IF' => 32,
			'INSERT' => 65,
			'CALL' => 66,
			"\"" => 30,
			"\$" => 29,
			"\${" => 63,
			'SET' => 23,
			'INCLUDE' => 62,
			'IDENT' => 22,
			"{" => 75,
			"(" => 74,
			'PROCESS' => 39,
			'NOT' => 37,
			'BLOCK' => 228,
			'LITERAL' => 34
		},
		GOTOS => {
			'item' => 43,
			'mdir' => 335,
			'switch' => 25,
			'atomexpr' => 26,
			'expr' => 237,
			'try' => 33,
			'condition' => 50,
			'setlist' => 51,
			'loop' => 14,
			'sterm' => 55,
			'node' => 18,
			'lterm' => 36,
			'assign' => 69,
			'javascript' => 19,
			'atomdir' => 70,
			'directive' => 229,
			'ident' => 167,
			'filter' => 21,
			'term' => 41,
			'wrapper' => 40
		}
	},
	{#State 314
		DEFAULT => -96
	},
	{#State 315
		DEFAULT => -95
	},
	{#State 316
		DEFAULT => -89
	},
	{#State 317
		ACTIONS => {
			'AND' => 121,
			'BINOP' => 119,
			'OR' => 120,
			'CMPOP' => 124,
			'DIV' => 122,
			"?" => 126,
			'CAT' => 118,
			"/" => 127,
			"+" => 123,
			'MOD' => 125
		},
		DEFAULT => -155
	},
	{#State 318
		DEFAULT => -102
	},
	{#State 319
		ACTIONS => {
			";" => 336
		}
	},
	{#State 320
		ACTIONS => {
			'PROCESS' => 39,
			"{" => 75,
			"(" => 74,
			'NOT' => 37,
			'BLOCK' => 71,
			'TEXT' => 35,
			'MACRO' => 67,
			'LITERAL' => 34,
			"\"" => 30,
			"\$" => 29,
			'IF' => 32,
			'RAW' => 31,
			'INSERT' => 65,
			'CALL' => 66,
			'rawperl' => 28,
			"\${" => 63,
			'IDENT' => 22,
			'VIEW' => 61,
			'INCLUDE' => 62,
			'SET' => 23,
			'WRAPPER' => 57,
			'JAVASCRIPT' => 58,
			'TRY' => 20,
			";" => -19,
			'META' => 54,
			'THROW' => 16,
			"[" => 52,
			'UNLESS' => 17,
			'FILTER' => 53,
			'WHILE' => 12,
			'CLEAR' => 49,
			'perl' => 48,
			'NUMBER' => 47,
			'RETURN' => 46,
			'SWITCH' => 8,
			'GET' => 45,
			'LAST' => 9,
			'USE' => 5,
			'NEXT' => 4,
			'STOP' => 3,
			'FOR' => 44,
			'REF' => 1,
			'DEFAULT' => 42,
			'DEBUG' => 2
		},
		DEFAULT => -3,
		GOTOS => {
			'node' => 18,
			'sterm' => 55,
			'assign' => 69,
			'capture' => 15,
			'lterm' => 36,
			'setlist' => 51,
			'chunk' => 68,
			'loop' => 14,
			'chunks' => 13,
			'condition' => 50,
			'view' => 11,
			'macro' => 60,
			'filter' => 21,
			'statement' => 59,
			'term' => 41,
			'wrapper' => 40,
			'directive' => 73,
			'ident' => 56,
			'block' => 337,
			'use' => 72,
			'atomdir' => 70,
			'javascript' => 19,
			'defblockname' => 7,
			'defblock' => 24,
			'switch' => 25,
			'item' => 43,
			'try' => 33,
			'anonblock' => 10,
			'raw' => 64,
			'expr' => 27,
			'atomexpr' => 26
		}
	},
	{#State 321
		ACTIONS => {
			";" => 338
		}
	},
	{#State 322
		DEFAULT => -53
	},
	{#State 323
		DEFAULT => -62
	},
	{#State 324
		DEFAULT => -48
	},
	{#State 325
		ACTIONS => {
			"\${" => 63,
			'rawperl' => 28,
			'INSERT' => 65,
			'CALL' => 66,
			'IF' => 32,
			'RAW' => 31,
			"\$" => 29,
			"\"" => 30,
			'SET' => 23,
			'INCLUDE' => 62,
			'VIEW' => 61,
			'IDENT' => 22,
			'BLOCK' => 71,
			'NOT' => 37,
			"(" => 74,
			"{" => 75,
			'PROCESS' => 39,
			'LITERAL' => 34,
			'MACRO' => 67,
			'TEXT' => 35,
			'LAST' => 9,
			'GET' => 45,
			'SWITCH' => 8,
			'RETURN' => 46,
			'NUMBER' => 47,
			'perl' => 48,
			'DEBUG' => 2,
			'REF' => 1,
			'DEFAULT' => 42,
			'FOR' => 44,
			'STOP' => 3,
			'NEXT' => 4,
			'USE' => 5,
			";" => -19,
			'TRY' => 20,
			'JAVASCRIPT' => 58,
			'WRAPPER' => 57,
			'CLEAR' => 49,
			'WHILE' => 12,
			'THROW' => 16,
			'UNLESS' => 17,
			'FILTER' => 53,
			"[" => 52,
			'META' => 54
		},
		DEFAULT => -3,
		GOTOS => {
			'condition' => 50,
			'chunks' => 13,
			'view' => 11,
			'capture' => 15,
			'assign' => 69,
			'lterm' => 36,
			'node' => 18,
			'sterm' => 55,
			'chunk' => 68,
			'loop' => 14,
			'setlist' => 51,
			'block' => 339,
			'atomdir' => 70,
			'javascript' => 19,
			'use' => 72,
			'wrapper' => 40,
			'filter' => 21,
			'term' => 41,
			'statement' => 59,
			'macro' => 60,
			'ident' => 56,
			'directive' => 73,
			'defblock' => 24,
			'defblockname' => 7,
			'switch' => 25,
			'item' => 43,
			'expr' => 27,
			'atomexpr' => 26,
			'anonblock' => 10,
			'try' => 33,
			'raw' => 64
		}
	},
	{#State 326
		ACTIONS => {
			'BINOP' => 119,
			'CMPOP' => 124,
			";" => 340,
			'OR' => 120,
			'MOD' => 125,
			"?" => 126,
			'AND' => 121,
			'DIV' => 122,
			"+" => 123,
			'CAT' => 118,
			"/" => 127
		}
	},
	{#State 327
		DEFAULT => -73
	},
	{#State 328
		ACTIONS => {
			'FINAL' => 268,
			'CATCH' => 269
		},
		DEFAULT => -74,
		GOTOS => {
			'final' => 341
		}
	},
	{#State 329
		ACTIONS => {
			";" => -19,
			'TRY' => 20,
			'WRAPPER' => 57,
			'JAVASCRIPT' => 58,
			'CLEAR' => 49,
			'WHILE' => 12,
			'FILTER' => 53,
			"[" => 52,
			'THROW' => 16,
			'UNLESS' => 17,
			'META' => 54,
			'SWITCH' => 8,
			'GET' => 45,
			'RETURN' => 46,
			'LAST' => 9,
			'NUMBER' => 47,
			'perl' => 48,
			'REF' => 1,
			'DEFAULT' => 42,
			'DEBUG' => 2,
			'STOP' => 3,
			'USE' => 5,
			'NEXT' => 4,
			'FOR' => 44,
			'BLOCK' => 71,
			'NOT' => 37,
			'PROCESS' => 39,
			"(" => 74,
			"{" => 75,
			'MACRO' => 67,
			'LITERAL' => 34,
			'TEXT' => 35,
			'rawperl' => 28,
			"\${" => 63,
			"\$" => 29,
			"\"" => 30,
			'INSERT' => 65,
			'CALL' => 66,
			'RAW' => 31,
			'IF' => 32,
			'VIEW' => 61,
			'IDENT' => 22,
			'INCLUDE' => 62,
			'SET' => 23
		},
		DEFAULT => -3,
		GOTOS => {
			'macro' => 60,
			'statement' => 59,
			'term' => 41,
			'filter' => 21,
			'wrapper' => 40,
			'directive' => 73,
			'ident' => 56,
			'block' => 342,
			'use' => 72,
			'javascript' => 19,
			'atomdir' => 70,
			'node' => 18,
			'sterm' => 55,
			'capture' => 15,
			'assign' => 69,
			'lterm' => 36,
			'setlist' => 51,
			'loop' => 14,
			'chunk' => 68,
			'chunks' => 13,
			'condition' => 50,
			'view' => 11,
			'try' => 33,
			'anonblock' => 10,
			'raw' => 64,
			'expr' => 27,
			'atomexpr' => 26,
			'defblock' => 24,
			'defblockname' => 7,
			'switch' => 25,
			'item' => 43
		}
	},
	{#State 330
		ACTIONS => {
			'TEXT' => 35,
			'MACRO' => 67,
			'LITERAL' => 34,
			'PROCESS' => 39,
			"(" => 74,
			"{" => 75,
			'BLOCK' => 71,
			'NOT' => 37,
			'VIEW' => 61,
			'IDENT' => 22,
			'INCLUDE' => 62,
			'SET' => 23,
			"\$" => 29,
			"\"" => 30,
			'CALL' => 66,
			'INSERT' => 65,
			'IF' => 32,
			'RAW' => 31,
			'rawperl' => 28,
			"\${" => 63,
			"[" => 52,
			'FILTER' => 53,
			'UNLESS' => 17,
			'THROW' => 16,
			'META' => 54,
			'CLEAR' => 49,
			'WHILE' => 12,
			'WRAPPER' => 57,
			'JAVASCRIPT' => 58,
			";" => -19,
			'TRY' => 20,
			'STOP' => 3,
			'USE' => 5,
			'NEXT' => 4,
			'FOR' => 44,
			'DEFAULT' => 42,
			'REF' => 1,
			'DEBUG' => 2,
			'NUMBER' => 47,
			'perl' => 48,
			'GET' => 45,
			'SWITCH' => 8,
			'RETURN' => 46,
			'LAST' => 9
		},
		DEFAULT => -3,
		GOTOS => {
			'block' => 343,
			'atomdir' => 70,
			'javascript' => 19,
			'use' => 72,
			'wrapper' => 40,
			'statement' => 59,
			'macro' => 60,
			'filter' => 21,
			'term' => 41,
			'ident' => 56,
			'directive' => 73,
			'condition' => 50,
			'chunks' => 13,
			'view' => 11,
			'assign' => 69,
			'capture' => 15,
			'lterm' => 36,
			'sterm' => 55,
			'node' => 18,
			'loop' => 14,
			'chunk' => 68,
			'setlist' => 51,
			'expr' => 27,
			'atomexpr' => 26,
			'anonblock' => 10,
			'try' => 33,
			'raw' => 64,
			'switch' => 25,
			'defblockname' => 7,
			'defblock' => 24,
			'item' => 43
		}
	},
	{#State 331
		DEFAULT => -46
	},
	{#State 332
		DEFAULT => -59
	},
	{#State 333
		DEFAULT => -94
	},
	{#State 334
		DEFAULT => -78
	},
	{#State 335
		DEFAULT => -91
	},
	{#State 336
		ACTIONS => {
			'BLOCK' => 71,
			'NOT' => 37,
			"{" => 75,
			"(" => 74,
			'PROCESS' => 39,
			'LITERAL' => 34,
			'MACRO' => 67,
			'TEXT' => 35,
			'rawperl' => 28,
			"\${" => 63,
			'IF' => 32,
			'RAW' => 31,
			'CALL' => 66,
			'INSERT' => 65,
			"\"" => 30,
			"\$" => 29,
			'INCLUDE' => 62,
			'SET' => 23,
			'IDENT' => 22,
			'VIEW' => 61,
			'TRY' => 20,
			";" => -19,
			'JAVASCRIPT' => 58,
			'WRAPPER' => 57,
			'WHILE' => 12,
			'CLEAR' => 49,
			'META' => 54,
			'UNLESS' => 17,
			'THROW' => 16,
			'FILTER' => 53,
			"[" => 52,
			'LAST' => 9,
			'RETURN' => 46,
			'GET' => 45,
			'SWITCH' => 8,
			'NUMBER' => 47,
			'perl' => 48,
			'DEBUG' => 2,
			'REF' => 1,
			'DEFAULT' => 42,
			'FOR' => 44,
			'NEXT' => 4,
			'USE' => 5,
			'STOP' => 3
		},
		DEFAULT => -3,
		GOTOS => {
			'chunk' => 68,
			'loop' => 14,
			'setlist' => 51,
			'lterm' => 36,
			'capture' => 15,
			'assign' => 69,
			'sterm' => 55,
			'node' => 18,
			'view' => 11,
			'condition' => 50,
			'chunks' => 13,
			'ident' => 56,
			'directive' => 73,
			'wrapper' => 40,
			'filter' => 21,
			'statement' => 59,
			'macro' => 60,
			'term' => 41,
			'javascript' => 19,
			'atomdir' => 70,
			'use' => 72,
			'block' => 344,
			'item' => 43,
			'defblockname' => 7,
			'defblock' => 24,
			'switch' => 25,
			'raw' => 64,
			'anonblock' => 10,
			'try' => 33,
			'atomexpr' => 26,
			'expr' => 27
		}
	},
	{#State 337
		DEFAULT => -56
	},
	{#State 338
		ACTIONS => {
			'NEXT' => 4,
			'USE' => 5,
			'STOP' => 3,
			'FOR' => 44,
			'DEFAULT' => 42,
			'REF' => 1,
			'DEBUG' => 2,
			'NUMBER' => 47,
			'perl' => 48,
			'RETURN' => 46,
			'SWITCH' => 8,
			'GET' => 45,
			'LAST' => 9,
			'META' => 54,
			'FILTER' => 53,
			"[" => 52,
			'THROW' => 16,
			'UNLESS' => 17,
			'WHILE' => 12,
			'CLEAR' => 49,
			'WRAPPER' => 57,
			'JAVASCRIPT' => 58,
			'TRY' => 20,
			";" => -19,
			'IDENT' => 22,
			'VIEW' => 61,
			'SET' => 23,
			'INCLUDE' => 62,
			"\"" => 30,
			"\$" => 29,
			'RAW' => 31,
			'IF' => 32,
			'CALL' => 66,
			'INSERT' => 65,
			'rawperl' => 28,
			"\${" => 63,
			'TEXT' => 35,
			'MACRO' => 67,
			'LITERAL' => 34,
			'PROCESS' => 39,
			"{" => 75,
			"(" => 74,
			'NOT' => 37,
			'BLOCK' => 71
		},
		DEFAULT => -3,
		GOTOS => {
			'item' => 43,
			'switch' => 25,
			'defblockname' => 7,
			'defblock' => 24,
			'atomexpr' => 26,
			'expr' => 27,
			'raw' => 64,
			'try' => 33,
			'anonblock' => 10,
			'view' => 11,
			'chunks' => 13,
			'condition' => 50,
			'setlist' => 51,
			'chunk' => 68,
			'loop' => 14,
			'sterm' => 55,
			'node' => 18,
			'assign' => 69,
			'capture' => 15,
			'lterm' => 36,
			'use' => 72,
			'atomdir' => 70,
			'javascript' => 19,
			'block' => 345,
			'directive' => 73,
			'ident' => 56,
			'macro' => 60,
			'term' => 41,
			'statement' => 59,
			'filter' => 21,
			'wrapper' => 40
		}
	},
	{#State 339
		DEFAULT => -51
	},
	{#State 340
		ACTIONS => {
			'LAST' => 9,
			'GET' => 45,
			'SWITCH' => 8,
			'RETURN' => 46,
			'perl' => 48,
			'NUMBER' => 47,
			'DEBUG' => 2,
			'REF' => 1,
			'DEFAULT' => 42,
			'FOR' => 44,
			'STOP' => 3,
			'USE' => 5,
			'NEXT' => 4,
			";" => -19,
			'TRY' => 20,
			'JAVASCRIPT' => 58,
			'WRAPPER' => 57,
			'CLEAR' => 49,
			'WHILE' => 12,
			"[" => 52,
			'FILTER' => 53,
			'UNLESS' => 17,
			'THROW' => 16,
			'META' => 54,
			"\${" => 63,
			'rawperl' => 28,
			'CALL' => 66,
			'INSERT' => 65,
			'RAW' => 31,
			'IF' => 32,
			"\$" => 29,
			"\"" => 30,
			'SET' => 23,
			'INCLUDE' => 62,
			'VIEW' => 61,
			'IDENT' => 22,
			'BLOCK' => 71,
			'NOT' => 37,
			"(" => 74,
			"{" => 75,
			'PROCESS' => 39,
			'LITERAL' => 34,
			'MACRO' => 67,
			'TEXT' => 35
		},
		DEFAULT => -3,
		GOTOS => {
			'sterm' => 55,
			'node' => 18,
			'capture' => 15,
			'lterm' => 36,
			'assign' => 69,
			'setlist' => 51,
			'chunk' => 68,
			'loop' => 14,
			'chunks' => 13,
			'condition' => 50,
			'view' => 11,
			'macro' => 60,
			'term' => 41,
			'filter' => 21,
			'statement' => 59,
			'wrapper' => 40,
			'directive' => 73,
			'ident' => 56,
			'block' => 346,
			'use' => 72,
			'javascript' => 19,
			'atomdir' => 70,
			'defblockname' => 7,
			'defblock' => 24,
			'switch' => 25,
			'item' => 43,
			'try' => 33,
			'anonblock' => 10,
			'raw' => 64,
			'expr' => 27,
			'atomexpr' => 26
		}
	},
	{#State 341
		DEFAULT => -72
	},
	{#State 342
		ACTIONS => {
			'FINAL' => 268,
			'CATCH' => 269
		},
		DEFAULT => -74,
		GOTOS => {
			'final' => 347
		}
	},
	{#State 343
		ACTIONS => {
			'CATCH' => 269,
			'FINAL' => 268
		},
		DEFAULT => -74,
		GOTOS => {
			'final' => 348
		}
	},
	{#State 344
		ACTIONS => {
			'CASE' => 292
		},
		DEFAULT => -57,
		GOTOS => {
			'case' => 349
		}
	},
	{#State 345
		DEFAULT => -55
	},
	{#State 346
		ACTIONS => {
			'ELSIF' => 297,
			'ELSE' => 296
		},
		DEFAULT => -52,
		GOTOS => {
			'else' => 350
		}
	},
	{#State 347
		DEFAULT => -71
	},
	{#State 348
		DEFAULT => -70
	},
	{#State 349
		DEFAULT => -54
	},
	{#State 350
		DEFAULT => -50
	}
]; 


#========================================================================
# Rules
#========================================================================

$RULES = [
	[#Rule 0
		 '$start', 2, undef
	],
	[#Rule 1
		 'template', 1,
sub
#line 68 "Parser.yp"
{ $factory->template($_[1])           }
	],
	[#Rule 2
		 'block', 1,
sub
#line 71 "Parser.yp"
{ $factory->block($_[1])              }
	],
	[#Rule 3
		 'block', 0,
sub
#line 72 "Parser.yp"
{ $factory->block()                   }
	],
	[#Rule 4
		 'chunks', 2,
sub
#line 75 "Parser.yp"
{ push(@{$_[1]}, $_[2]) 
					if defined $_[2]; $_[1]           }
	],
	[#Rule 5
		 'chunks', 1,
sub
#line 77 "Parser.yp"
{ defined $_[1] ? [ $_[1] ] : [ ]     }
	],
	[#Rule 6
		 'chunk', 1,
sub
#line 80 "Parser.yp"
{ $factory->textblock($_[1])          }
	],
	[#Rule 7
		 'chunk', 2,
sub
#line 81 "Parser.yp"
{ return '' unless $_[1];
                           $_[0]->location() . $_[1];
                         }
	],
	[#Rule 8
		 'statement', 1, undef
	],
	[#Rule 9
		 'statement', 1, undef
	],
	[#Rule 10
		 'statement', 1, undef
	],
	[#Rule 11
		 'statement', 1, undef
	],
	[#Rule 12
		 'statement', 1, undef
	],
	[#Rule 13
		 'statement', 1, undef
	],
	[#Rule 14
		 'statement', 1, undef
	],
	[#Rule 15
		 'statement', 1, undef
	],
	[#Rule 16
		 'statement', 1, undef
	],
	[#Rule 17
		 'statement', 1,
sub
#line 95 "Parser.yp"
{ $factory->get($_[1])                }
	],
	[#Rule 18
		 'statement', 2,
sub
#line 96 "Parser.yp"
{ $_[0]->add_metadata($_[2]);         }
	],
	[#Rule 19
		 'statement', 0, undef
	],
	[#Rule 20
		 'directive', 1,
sub
#line 100 "Parser.yp"
{ $factory->set($_[1])                }
	],
	[#Rule 21
		 'directive', 1, undef
	],
	[#Rule 22
		 'directive', 1, undef
	],
	[#Rule 23
		 'directive', 1, undef
	],
	[#Rule 24
		 'directive', 1, undef
	],
	[#Rule 25
		 'directive', 1, undef
	],
	[#Rule 26
		 'directive', 1, undef
	],
	[#Rule 27
		 'directive', 1, undef
	],
	[#Rule 28
		 'atomexpr', 1,
sub
#line 115 "Parser.yp"
{ $factory->get($_[1])                }
	],
	[#Rule 29
		 'atomexpr', 1, undef
	],
	[#Rule 30
		 'atomdir', 2,
sub
#line 119 "Parser.yp"
{ $factory->get($_[2])                }
	],
	[#Rule 31
		 'atomdir', 2,
sub
#line 120 "Parser.yp"
{ $factory->call($_[2])               }
	],
	[#Rule 32
		 'atomdir', 2,
sub
#line 121 "Parser.yp"
{ $factory->set($_[2])                }
	],
	[#Rule 33
		 'atomdir', 2,
sub
#line 122 "Parser.yp"
{ $factory->default($_[2])            }
	],
	[#Rule 34
		 'atomdir', 2,
sub
#line 123 "Parser.yp"
{ $factory->insert($_[2])             }
	],
	[#Rule 35
		 'atomdir', 2,
sub
#line 124 "Parser.yp"
{ $factory->include($_[2])            }
	],
	[#Rule 36
		 'atomdir', 2,
sub
#line 125 "Parser.yp"
{ $factory->process($_[2])            }
	],
	[#Rule 37
		 'atomdir', 2,
sub
#line 126 "Parser.yp"
{ $factory->throw($_[2])              }
	],
	[#Rule 38
		 'atomdir', 1,
sub
#line 127 "Parser.yp"
{ $factory->return()                  }
	],
	[#Rule 39
		 'atomdir', 1,
sub
#line 128 "Parser.yp"
{ $factory->stop()                    }
	],
	[#Rule 40
		 'atomdir', 1,
sub
#line 129 "Parser.yp"
{ $factory->clear()                   }
	],
	[#Rule 41
		 'atomdir', 1,
sub
#line 130 "Parser.yp"
{ $factory->break()                   }
	],
	[#Rule 42
		 'atomdir', 1,
sub
#line 131 "Parser.yp"
{ $factory->next()                    }
	],
	[#Rule 43
		 'atomdir', 2,
sub
#line 132 "Parser.yp"
{ if ($_[2]->[0]->[0] =~ /^'(on|off)'$/) {
				          $_[0]->{ DEBUG_DIRS } = ($1 eq 'on');
					  $factory->debug($_[2]);
				      }
				      else {
					  $_[0]->{ DEBUG_DIRS } ? $factory->debug($_[2]) : '';
				      }
				    }
	],
	[#Rule 44
		 'atomdir', 1, undef
	],
	[#Rule 45
		 'atomdir', 1, undef
	],
	[#Rule 46
		 'condition', 6,
sub
#line 145 "Parser.yp"
{ $factory->if(@_[2, 4, 5])           }
	],
	[#Rule 47
		 'condition', 3,
sub
#line 146 "Parser.yp"
{ $factory->if(@_[3, 1])              }
	],
	[#Rule 48
		 'condition', 6,
sub
#line 148 "Parser.yp"
{ $factory->if("($_[2]) == false", @_[4, 5])  }
	],
	[#Rule 49
		 'condition', 3,
sub
#line 149 "Parser.yp"
{ $factory->if("($_[3]) == false", $_[1])     }
	],
	[#Rule 50
		 'else', 5,
sub
#line 153 "Parser.yp"
{ unshift(@{$_[5]}, [ @_[2, 4] ]);
				      $_[5];                              }
	],
	[#Rule 51
		 'else', 3,
sub
#line 155 "Parser.yp"
{ [ $_[3] ]                           }
	],
	[#Rule 52
		 'else', 0,
sub
#line 156 "Parser.yp"
{ [ undef ]                           }
	],
	[#Rule 53
		 'switch', 6,
sub
#line 160 "Parser.yp"
{ $factory->switch(@_[2, 5])          }
	],
	[#Rule 54
		 'case', 5,
sub
#line 164 "Parser.yp"
{ unshift(@{$_[5]}, [ @_[2, 4] ]); 
				      $_[5];                              }
	],
	[#Rule 55
		 'case', 4,
sub
#line 166 "Parser.yp"
{ [ $_[4] ]                           }
	],
	[#Rule 56
		 'case', 3,
sub
#line 167 "Parser.yp"
{ [ $_[3] ]                           }
	],
	[#Rule 57
		 'case', 0,
sub
#line 168 "Parser.yp"
{ [ undef ]                           }
	],
	[#Rule 58
		 '@1-3', 0,
sub
#line 171 "Parser.yp"
{ $_[0]->{ INFOR }++                  }
	],
	[#Rule 59
		 'loop', 6,
sub
#line 172 "Parser.yp"
{ $_[0]->{ INFOR }--;
				      $factory->foreach(@{$_[2]}, $_[5])  }
	],
	[#Rule 60
		 'loop', 3,
sub
#line 176 "Parser.yp"
{ $factory->foreach(@{$_[3]}, $_[1])  }
	],
	[#Rule 61
		 '@2-3', 0,
sub
#line 177 "Parser.yp"
{ $_[0]->{ INWHILE }++                }
	],
	[#Rule 62
		 'loop', 6,
sub
#line 178 "Parser.yp"
{ $_[0]->{ INWHILE }--;
                                      $factory->while(@_[2, 5])           }
	],
	[#Rule 63
		 'loop', 3,
sub
#line 180 "Parser.yp"
{ $factory->while(@_[3, 1])           }
	],
	[#Rule 64
		 'loopvar', 4,
sub
#line 183 "Parser.yp"
{ [ @_[1, 3, 4] ]                     }
	],
	[#Rule 65
		 'loopvar', 4,
sub
#line 184 "Parser.yp"
{ [ @_[1, 3, 4] ]                     }
	],
	[#Rule 66
		 'loopvar', 2,
sub
#line 185 "Parser.yp"
{ [ 0, @_[1, 2] ]                     }
	],
	[#Rule 67
		 'wrapper', 5,
sub
#line 189 "Parser.yp"
{ $factory->wrapper(@_[2, 4])         }
	],
	[#Rule 68
		 'wrapper', 3,
sub
#line 191 "Parser.yp"
{ $factory->wrapper(@_[3, 1])         }
	],
	[#Rule 69
		 'try', 5,
sub
#line 195 "Parser.yp"
{ $factory->try(@_[3, 4])             }
	],
	[#Rule 70
		 'final', 5,
sub
#line 199 "Parser.yp"
{ unshift(@{$_[5]}, [ @_[2,4] ]);
				      $_[5];                              }
	],
	[#Rule 71
		 'final', 5,
sub
#line 202 "Parser.yp"
{ unshift(@{$_[5]}, [ undef, $_[4] ]);
				      $_[5];                              }
	],
	[#Rule 72
		 'final', 4,
sub
#line 205 "Parser.yp"
{ unshift(@{$_[4]}, [ undef, $_[3] ]);
				      $_[4];                              }
	],
	[#Rule 73
		 'final', 3,
sub
#line 207 "Parser.yp"
{ [ $_[3] ]                           }
	],
	[#Rule 74
		 'final', 0,
sub
#line 208 "Parser.yp"
{ [ 0 ] }
	],
	[#Rule 75
		 'use', 2,
sub
#line 211 "Parser.yp"
{ $factory->use($_[2])                }
	],
	[#Rule 76
		 'raw', 2,
sub
#line 214 "Parser.yp"
{ $factory->raw($_[2])                }
	],
	[#Rule 77
		 '@3-3', 0,
sub
#line 217 "Parser.yp"
{ $_[0]->push_defblock();		  }
	],
	[#Rule 78
		 'view', 6,
sub
#line 218 "Parser.yp"
{ $factory->view(@_[2,5], 
						     $_[0]->pop_defblock) }
	],
	[#Rule 79
		 '@4-2', 0,
sub
#line 222 "Parser.yp"
{ ${$_[0]->{ INJAVASCRIPT }}++;             }
	],
	[#Rule 80
		 'javascript', 5,
sub
#line 223 "Parser.yp"
{ ${$_[0]->{ INJAVASCRIPT }}--;
				      $_[0]->{ EVAL_JAVASCRIPT } 
				      ? $factory->javascript($_[4])             
				      : $factory->no_javascript();              }
	],
	[#Rule 81
		 'filter', 5,
sub
#line 230 "Parser.yp"
{ $factory->filter(@_[2,4])           }
	],
	[#Rule 82
		 'filter', 3,
sub
#line 232 "Parser.yp"
{ $factory->filter(@_[3,1])           }
	],
	[#Rule 83
		 'defblock', 5,
sub
#line 237 "Parser.yp"
{ my $name = join('/', @{ $_[0]->{ DEFBLOCKS } });
				      pop(@{ $_[0]->{ DEFBLOCKS } });
				      $_[0]->define_block($name, $_[4]); 
				      undef
				    }
	],
	[#Rule 84
		 'defblockname', 2,
sub
#line 244 "Parser.yp"
{ push(@{ $_[0]->{ DEFBLOCKS } }, $_[2]);
				      $_[2];
				    }
	],
	[#Rule 85
		 'blockname', 1, undef
	],
	[#Rule 86
		 'blockname', 1,
sub
#line 250 "Parser.yp"
{ $_[1] =~ s/^'(.*)'$/$1/; $_[1]      }
	],
	[#Rule 87
		 'blockargs', 1, undef
	],
	[#Rule 88
		 'blockargs', 0, undef
	],
	[#Rule 89
		 'anonblock', 5,
sub
#line 258 "Parser.yp"
{ local $" = ', ';
				      print STDERR "experimental block args: [@{ $_[2] }]\n"
					  if $_[2];
				      $factory->anon_block($_[4])         }
	],
	[#Rule 90
		 'capture', 3,
sub
#line 264 "Parser.yp"
{ $factory->capture(@_[1, 3])         }
	],
	[#Rule 91
		 'macro', 6,
sub
#line 268 "Parser.yp"
{ $factory->macro(@_[2, 6, 4])        }
	],
	[#Rule 92
		 'macro', 3,
sub
#line 269 "Parser.yp"
{ $factory->macro(@_[2, 3])           }
	],
	[#Rule 93
		 'mdir', 1, undef
	],
	[#Rule 94
		 'mdir', 4,
sub
#line 273 "Parser.yp"
{ $_[3]                               }
	],
	[#Rule 95
		 'margs', 2,
sub
#line 276 "Parser.yp"
{ push(@{$_[1]}, $_[2]); $_[1]        }
	],
	[#Rule 96
		 'margs', 2,
sub
#line 277 "Parser.yp"
{ $_[1]                               }
	],
	[#Rule 97
		 'margs', 1,
sub
#line 278 "Parser.yp"
{ [ $_[1] ]                           }
	],
	[#Rule 98
		 'metadata', 2,
sub
#line 281 "Parser.yp"
{ push(@{$_[1]}, @{$_[2]}); $_[1]     }
	],
	[#Rule 99
		 'metadata', 2, undef
	],
	[#Rule 100
		 'metadata', 1, undef
	],
	[#Rule 101
		 'meta', 3,
sub
#line 286 "Parser.yp"
{ for ($_[3]) { s/^'//; s/'$//; 
						       s/\\'/'/g  }; 
					 [ @_[1,3] ] }
	],
	[#Rule 102
		 'meta', 5,
sub
#line 289 "Parser.yp"
{ [ @_[1,4] ] }
	],
	[#Rule 103
		 'meta', 3,
sub
#line 290 "Parser.yp"
{ [ @_[1,3] ] }
	],
	[#Rule 104
		 'term', 1, undef
	],
	[#Rule 105
		 'term', 1, undef
	],
	[#Rule 106
		 'lterm', 3,
sub
#line 302 "Parser.yp"
{ "[ $_[2] ]"                         }
	],
	[#Rule 107
		 'lterm', 3,
sub
#line 303 "Parser.yp"
{ "[ $_[2] ]"                         }
	],
	[#Rule 108
		 'lterm', 2,
sub
#line 304 "Parser.yp"
{ "[ ]"                               }
	],
	[#Rule 109
		 'lterm', 3,
sub
#line 305 "Parser.yp"
{ "{ $_[2]  }"                        }
	],
	[#Rule 110
		 'sterm', 1,
sub
#line 308 "Parser.yp"
{ $factory->ident($_[1])              }
	],
	[#Rule 111
		 'sterm', 2,
sub
#line 309 "Parser.yp"
{ $factory->identref($_[2])           }
	],
	[#Rule 112
		 'sterm', 3,
sub
#line 310 "Parser.yp"
{ $factory->quoted($_[2])             }
	],
	[#Rule 113
		 'sterm', 1, undef
	],
	[#Rule 114
		 'sterm', 1, undef
	],
	[#Rule 115
		 'list', 2,
sub
#line 315 "Parser.yp"
{ "$_[1], $_[2]"                      }
	],
	[#Rule 116
		 'list', 2, undef
	],
	[#Rule 117
		 'list', 1, undef
	],
	[#Rule 118
		 'range', 3,
sub
#line 320 "Parser.yp"
{ $_[1] . '..' . $_[3]                }
	],
	[#Rule 119
		 'hash', 1, undef
	],
	[#Rule 120
		 'hash', 0,
sub
#line 325 "Parser.yp"
{ "" }
	],
	[#Rule 121
		 'params', 2,
sub
#line 328 "Parser.yp"
{ "$_[1], $_[2]"                      }
	],
	[#Rule 122
		 'params', 2, undef
	],
	[#Rule 123
		 'params', 1, undef
	],
	[#Rule 124
		 'param', 3,
sub
#line 333 "Parser.yp"
{ "$_[1]: $_[3]"                    }
	],
	[#Rule 125
		 'param', 3,
sub
#line 334 "Parser.yp"
{ "$_[1]: $_[3]"                    }
	],
	[#Rule 126
		 'ident', 3,
sub
#line 337 "Parser.yp"
{ push(@{$_[1]}, @{$_[3]}); $_[1]     }
	],
	[#Rule 127
		 'ident', 3,
sub
#line 338 "Parser.yp"
{ push(@{$_[1]}, 
					   map {($_, 0)} split(/\./, $_[3]));
				      $_[1];			          }
	],
	[#Rule 128
		 'ident', 1, undef
	],
	[#Rule 129
		 'node', 1,
sub
#line 344 "Parser.yp"
{ [ $_[1], 0 ]                        }
	],
	[#Rule 130
		 'node', 4,
sub
#line 345 "Parser.yp"
{ [ $_[1], $factory->args($_[3]) ]    }
	],
	[#Rule 131
		 'item', 1,
sub
#line 348 "Parser.yp"
{ "'$_[1]'"                           }
	],
	[#Rule 132
		 'item', 3,
sub
#line 349 "Parser.yp"
{ $_[2]                               }
	],
	[#Rule 133
		 'item', 2,
sub
#line 350 "Parser.yp"
{ $_[0]->{ V1DOLLAR }
				       ? "'$_[2]'" 
				       : $factory->ident(["'$_[2]'", 0])  }
	],
	[#Rule 134
		 'expr', 3,
sub
#line 355 "Parser.yp"
{ "$_[1] $_[2] $_[3]"                 }
	],
	[#Rule 135
		 'expr', 3,
sub
#line 356 "Parser.yp"
{ "$_[1] $_[2] $_[3]"                 }
	],
	[#Rule 136
		 'expr', 3,
sub
#line 357 "Parser.yp"
{ "$_[1] $_[2] $_[3]"                 }
	],
	[#Rule 137
		 'expr', 3,
sub
#line 358 "Parser.yp"
{ "Math.floor($_[1] / $_[3])"                }
	],
	[#Rule 138
		 'expr', 3,
sub
#line 359 "Parser.yp"
{ "$_[1] % $_[3]"                     }
	],
	[#Rule 139
		 'expr', 3,
sub
#line 360 "Parser.yp"
{ "$_[1] $CMPOP{ $_[2] } $_[3]"       }
	],
	[#Rule 140
		 'expr', 3,
sub
#line 361 "Parser.yp"
{ "$_[1]  + $_[3]"                    }
	],
	[#Rule 141
		 'expr', 3,
sub
#line 362 "Parser.yp"
{ "$_[1] && $_[3]"                    }
	],
	[#Rule 142
		 'expr', 3,
sub
#line 363 "Parser.yp"
{ "$_[1] || $_[3]"                    }
	],
	[#Rule 143
		 'expr', 2,
sub
#line 364 "Parser.yp"
{ "! $_[2]"                           }
	],
	[#Rule 144
		 'expr', 5,
sub
#line 365 "Parser.yp"
{ "$_[1] ? $_[3] : $_[5]"             }
	],
	[#Rule 145
		 'expr', 3,
sub
#line 366 "Parser.yp"
{ $factory->assign(@{$_[2]})          }
	],
	[#Rule 146
		 'expr', 3,
sub
#line 367 "Parser.yp"
{ "($_[2])"                           }
	],
	[#Rule 147
		 'expr', 1, undef
	],
	[#Rule 148
		 'setlist', 2,
sub
#line 371 "Parser.yp"
{ push(@{$_[1]}, @{$_[2]}); $_[1]     }
	],
	[#Rule 149
		 'setlist', 2, undef
	],
	[#Rule 150
		 'setlist', 1, undef
	],
	[#Rule 151
		 'assign', 3,
sub
#line 377 "Parser.yp"
{ [ $_[1], $_[3] ]                    }
	],
	[#Rule 152
		 'assign', 3,
sub
#line 378 "Parser.yp"
{ [ @_[1,3] ]                         }
	],
	[#Rule 153
		 'args', 2,
sub
#line 385 "Parser.yp"
{ push(@{$_[1]}, $_[2]); $_[1]        }
	],
	[#Rule 154
		 'args', 2,
sub
#line 386 "Parser.yp"
{ push(@{$_[1]->[0]}, $_[2]); $_[1]   }
	],
	[#Rule 155
		 'args', 4,
sub
#line 387 "Parser.yp"
{ push(@{$_[1]->[0]}, "'', " . 
				      $factory->assign(@_[2,4])); $_[1]  }
	],
	[#Rule 156
		 'args', 2,
sub
#line 389 "Parser.yp"
{ $_[1]                               }
	],
	[#Rule 157
		 'args', 0,
sub
#line 390 "Parser.yp"
{ [ [ ] ]                             }
	],
	[#Rule 158
		 'lnameargs', 3,
sub
#line 400 "Parser.yp"
{ push(@{$_[3]}, $_[1]); $_[3]        }
	],
	[#Rule 159
		 'lnameargs', 1, undef
	],
	[#Rule 160
		 'lvalue', 1, undef
	],
	[#Rule 161
		 'lvalue', 3,
sub
#line 405 "Parser.yp"
{ $factory->quoted($_[2])             }
	],
	[#Rule 162
		 'lvalue', 1, undef
	],
	[#Rule 163
		 'nameargs', 3,
sub
#line 409 "Parser.yp"
{ [ [$factory->ident($_[2])], $_[3] ]   }
	],
	[#Rule 164
		 'nameargs', 2,
sub
#line 410 "Parser.yp"
{ [ @_[1,2] ] }
	],
	[#Rule 165
		 'nameargs', 4,
sub
#line 411 "Parser.yp"
{ [ @_[1,3] ] }
	],
	[#Rule 166
		 'names', 3,
sub
#line 414 "Parser.yp"
{ push(@{$_[1]}, $_[3]); $_[1] }
	],
	[#Rule 167
		 'names', 1,
sub
#line 415 "Parser.yp"
{ [ $_[1] ]                    }
	],
	[#Rule 168
		 'name', 3,
sub
#line 418 "Parser.yp"
{ $factory->quoted($_[2])  }
	],
	[#Rule 169
		 'name', 1,
sub
#line 419 "Parser.yp"
{ "'$_[1]'" }
	],
	[#Rule 170
		 'name', 1, undef
	],
	[#Rule 171
		 'filename', 3,
sub
#line 431 "Parser.yp"
{ "$_[1].$_[3]" }
	],
	[#Rule 172
		 'filename', 1, undef
	],
	[#Rule 173
		 'filepart', 1, undef
	],
	[#Rule 174
		 'filepart', 1, undef
	],
	[#Rule 175
		 'filepart', 1, undef
	],
	[#Rule 176
		 'quoted', 2,
sub
#line 445 "Parser.yp"
{ push(@{$_[1]}, $_[2]) 
				          if defined $_[2]; $_[1]         }
	],
	[#Rule 177
		 'quoted', 0,
sub
#line 447 "Parser.yp"
{ [ ]                                 }
	],
	[#Rule 178
		 'quotable', 1,
sub
#line 450 "Parser.yp"
{ $factory->ident($_[1])              }
	],
	[#Rule 179
		 'quotable', 1,
sub
#line 451 "Parser.yp"
{ $factory->text($_[1])               }
	],
	[#Rule 180
		 'quotable', 1,
sub
#line 452 "Parser.yp"
{ undef                               }
	]
];

1;
